import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const helpTokens = {
  PRIMARY: '#0342D1',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE: '#747686',
  OUTLINE_VARIANT: 'rgba(196, 197, 215, 0.3)',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SURFACE_CONTAINER: '#EDEEEF',
  SECONDARY: '#585E72',
  RESOLVED_BG: '#D1FAE5',
  RESOLVED_TEXT: '#065F46',
  PROGRESS_BG: '#FEF3C7',
  PROGRESS_TEXT: '#92400E',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: helpTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    minHeight: 64,
    backgroundColor: helpTokens.SURFACE,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#C4C5D7',
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: helpTokens.PRIMARY,
    flexShrink: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.sectionGap,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  searchWrap: {
    position: 'relative',
    justifyContent: 'center',
  },
  searchIcon: {
    position: 'absolute',
    left: spacing.lg,
    zIndex: 1,
  },
  searchInput: {
    height: 56,
    paddingLeft: 48,
    paddingRight: spacing.lg,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: '#C4C5D7',
    backgroundColor: colors.white,
    fontSize: 16,
    lineHeight: 24,
    color: helpTokens.ON_SURFACE,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 8, offsetY: 2, elevation: 1 }),
  },
  section: {
    gap: spacing.cardGap,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  sectionTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: helpTokens.ON_SURFACE,
    flexShrink: 1,
  },
  viewAll: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: helpTokens.PRIMARY,
  },
  categoriesGrid: {
    gap: spacing.cardGap,
  },
  categoryCard: {
    padding: spacing.xxl,
    borderRadius: layout.radiusLg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: helpTokens.OUTLINE_VARIANT,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  categoryIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(3, 66, 209, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.lg,
  },
  categoryTitle: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: helpTokens.ON_SURFACE_VARIANT,
    marginBottom: spacing.xs,
  },
  categorySubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: helpTokens.OUTLINE,
  },
  ticketsList: {
    gap: spacing.lg,
  },
  ticketCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    padding: spacing.xl,
    borderRadius: layout.radiusLg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: helpTokens.OUTLINE_VARIANT,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  ticketLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
  },
  ticketIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: helpTokens.SURFACE_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ticketMeta: {
    flex: 1,
    gap: 2,
  },
  ticketTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: helpTokens.ON_SURFACE,
  },
  ticketDate: {
    fontSize: 14,
    lineHeight: 20,
    color: helpTokens.OUTLINE,
  },
  statusBadge: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
  },
  statusResolved: {
    backgroundColor: helpTokens.RESOLVED_BG,
  },
  statusProgress: {
    backgroundColor: helpTokens.PROGRESS_BG,
  },
  statusLabel: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  statusLabelResolved: {
    color: helpTokens.RESOLVED_TEXT,
  },
  statusLabelProgress: {
    color: helpTokens.PROGRESS_TEXT,
  },
  contactActions: {
    gap: spacing.lg,
    paddingTop: spacing.xxxl,
  },
  chatButton: {
    height: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: helpTokens.PRIMARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    ...createShadow({ color: colors.shadow, opacity: 0.12, radius: 10, offsetY: 4, elevation: 3 }),
  },
  chatLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.white,
  },
  emailButton: {
    height: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: helpTokens.SECONDARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
  },
  emailLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: helpTokens.SECONDARY,
  },
  emptyState: {
    paddingVertical: spacing.lg,
  },
  emptyText: {
    fontSize: 14,
    lineHeight: 20,
    color: helpTokens.OUTLINE,
    textAlign: 'center',
  },
});
