import { StyleSheet } from 'react-native';

import { colors } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const identityVerifiedTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY: '#FFFFFF',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  SURFACE: '#F8F9FA',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  SURFACE_LOWEST: '#FFFFFF',
  SECONDARY_CONTAINER: '#DADFF7',
  ON_SECONDARY_CONTAINER: '#5C6276',
  OUTLINE_VARIANT: '#C4C5D7',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: identityVerifiedTokens.SURFACE,
  },
  header: {
    height: 64,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: identityVerifiedTokens.SURFACE,
    ...createShadow({ color: colors.shadow, opacity: 0.06, radius: 6, offsetY: 2, elevation: 2 }),
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 22,
    lineHeight: 30,
    fontWeight: '700',
    color: identityVerifiedTokens.PRIMARY,
  },
  headerSpacer: {
    width: 40,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    width: '100%',
    maxWidth: 420,
    alignItems: 'center',
  },
  heroWrap: {
    width: 128,
    height: 128,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 48,
  },
  pulseGlow: {
    position: 'absolute',
    width: 192,
    height: 192,
    borderRadius: 96,
    backgroundColor: identityVerifiedTokens.PRIMARY,
    opacity: 0.12,
  },
  checkCircle: {
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: identityVerifiedTokens.PRIMARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({ color: '#0342D1', opacity: 0.28, radius: 16, offsetY: 8, elevation: 8 }),
  },
  copyBlock: {
    alignItems: 'center',
    marginBottom: 40,
    gap: 16,
  },
  title: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    letterSpacing: -0.2,
    color: identityVerifiedTokens.ON_SURFACE,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400',
    color: identityVerifiedTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
    maxWidth: 320,
  },
  trustCard: {
    width: '100%',
    borderRadius: 12,
    backgroundColor: identityVerifiedTokens.SURFACE_LOWEST,
    borderWidth: 1,
    borderColor: identityVerifiedTokens.OUTLINE_VARIANT,
    padding: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 48,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 8, offsetY: 2, elevation: 2 }),
  },
  trustLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flex: 1,
  },
  trustIcon: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: identityVerifiedTokens.SECONDARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trustLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: identityVerifiedTokens.ON_SURFACE_VARIANT,
    textTransform: 'uppercase',
  },
  trustValue: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: identityVerifiedTokens.PRIMARY,
  },
  trustRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(3, 66, 209, 0.1)',
  },
  statusBadgeLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: identityVerifiedTokens.PRIMARY,
    textTransform: 'uppercase',
  },
  badgeUnlocked: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
    color: identityVerifiedTokens.ON_SURFACE_VARIANT,
  },
  ctaButton: {
    width: '100%',
    minHeight: 56,
    borderRadius: 12,
    backgroundColor: identityVerifiedTokens.PRIMARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    ...createShadow({ color: '#0342D1', opacity: 0.28, radius: 14, offsetY: 8, elevation: 8 }),
  },
  ctaLabel: {
    fontSize: 22,
    lineHeight: 30,
    fontWeight: '600',
    color: identityVerifiedTokens.ON_PRIMARY,
  },
  confettiDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 2,
  },
});
