import { StyleSheet } from 'react-native';
import { colors, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

const SURFACE = '#F8F9FF';
const ON_SURFACE = '#191C1D';
const ON_SURFACE_VARIANT = '#45464D';
const OUTLINE_VARIANT = '#C6C6CD';
const SURFACE_CONTAINER_HIGH = '#DCE9FF';
const PRIMARY_CONTAINER = '#131B2E';
const TRACK_BLUE = '#335EEA';
const RADIUS_XL = 12;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: SURFACE,
  },
  header: {
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    backgroundColor: SURFACE,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.06,
      radius: 4,
      offsetY: 1,
      elevation: 2,
    }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.listGap,
  },
  brandAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: PRIMARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandName: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: colors.primary,
  },
  notifyBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 32,
  },
  hero: {
    alignItems: 'center',
    marginBottom: spacing.sectionGap,
  },
  checkWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: SURFACE_CONTAINER_HIGH,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.cardGap,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.08,
      radius: 6,
      offsetY: 2,
      elevation: 2,
    }),
  },
  title: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: ON_SURFACE,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400',
    color: ON_SURFACE_VARIANT,
    textAlign: 'center',
  },
  driverCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.cardGap,
    backgroundColor: colors.white,
    borderRadius: RADIUS_XL,
    padding: 16,
    marginBottom: spacing.sectionGap,
    borderWidth: 1,
    borderColor: 'rgba(198, 198, 205, 0.3)',
    ...createShadow({
      color: colors.shadow,
      opacity: 0.06,
      radius: 6,
      offsetY: 2,
      elevation: 2,
    }),
  },
  avatarWrap: {
    position: 'relative',
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: PRIMARY_CONTAINER,
  },
  verifiedBadge: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 2,
  },
  driverMeta: {
    flex: 1,
  },
  driverTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 2,
  },
  driverName: {
    flex: 1,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: ON_SURFACE,
  },
  ratingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(19, 27, 46, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  ratingText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    letterSpacing: 0.14,
    color: PRIMARY_CONTAINER,
  },
  vehicleText: {
    fontSize: 14,
    lineHeight: 20,
    color: ON_SURFACE_VARIANT,
    marginBottom: 4,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.cardGap,
  },
  contactBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  contactLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    letterSpacing: 0.14,
    color: colors.primary,
  },
  tripCard: {
    backgroundColor: colors.white,
    borderRadius: RADIUS_XL,
    padding: 16,
    marginBottom: spacing.sectionGap,
    borderWidth: 1,
    borderColor: 'rgba(198, 198, 205, 0.3)',
    ...createShadow({
      color: colors.shadow,
      opacity: 0.06,
      radius: 6,
      offsetY: 2,
      elevation: 2,
    }),
  },
  tripMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 16,
    marginBottom: spacing.sectionGap,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(198, 198, 205, 0.2)',
  },
  tripMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tripMetaText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    letterSpacing: 0.14,
    color: ON_SURFACE,
  },
  routeList: {
    gap: spacing.sectionGap,
    paddingLeft: 4,
    position: 'relative',
  },
  routeDash: {
    position: 'absolute',
    left: 7,
    top: 24,
    bottom: 24,
    width: 2,
    borderStyle: 'dashed',
    borderLeftWidth: 2,
    borderColor: OUTLINE_VARIANT,
  },
  stopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.cardGap,
  },
  stopDotOuter: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: SURFACE,
    marginTop: 4,
    zIndex: 1,
  },
  stopDotFilled: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.primary,
    marginTop: 4,
    zIndex: 1,
  },
  stopContent: {
    flex: 1,
  },
  stopLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    letterSpacing: 0.24,
    textTransform: 'uppercase',
    color: ON_SURFACE_VARIANT,
    marginBottom: 2,
  },
  stopTitle: {
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '400',
    color: ON_SURFACE,
  },
  stopAddress: {
    fontSize: 14,
    lineHeight: 20,
    color: ON_SURFACE_VARIANT,
  },
  mapWrap: {
    height: 192,
    borderRadius: RADIUS_XL,
    overflow: 'hidden',
    marginBottom: spacing.sectionGap,
    backgroundColor: '#CBDBF5',
    ...createShadow({
      color: colors.shadow,
      opacity: 0.06,
      radius: 6,
      offsetY: 2,
      elevation: 2,
    }),
  },
  mapImage: {
    width: '100%',
    height: '100%',
  },
  etaBadge: {
    position: 'absolute',
    top: 16,
    left: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    ...createShadow({
      color: colors.shadow,
      opacity: 0.08,
      radius: 4,
      offsetY: 1,
      elevation: 2,
    }),
  },
  etaDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#BA1A1A',
  },
  etaText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.24,
    color: ON_SURFACE,
  },
  locateBtn: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: colors.shadow,
      opacity: 0.12,
      radius: 8,
      offsetY: 2,
      elevation: 4,
    }),
  },
  actions: {
    gap: spacing.listGap,
  },
  trackButton: {
    width: '100%',
    minHeight: 56,
    borderRadius: RADIUS_XL,
    backgroundColor: TRACK_BLUE,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    ...createShadow({
      color: TRACK_BLUE,
      opacity: 0.28,
      radius: 12,
      offsetY: 6,
      elevation: 6,
    }),
  },
  trackLabel: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: colors.white,
  },
  optionsButton: {
    width: '100%',
    minHeight: 48,
    borderRadius: RADIUS_XL,
    borderWidth: 1,
    borderColor: OUTLINE_VARIANT,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  optionsLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    letterSpacing: 0.14,
    color: ON_SURFACE,
  },
});
