import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    backgroundColor: '#F8F9FA',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: colors.primary,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xxxl,
    alignItems: 'center',
    gap: spacing.xxl,
  },
  hero: {
    alignItems: 'center',
    gap: spacing.lg,
  },
  cancelIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#FFDAD6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heading: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: '#191C1D',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: '#434655',
    textAlign: 'center',
    maxWidth: 320,
  },
  summaryCard: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: '#C4C5D7',
    padding: spacing.xxl,
    gap: spacing.sm,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.05,
      radius: 20,
      offsetY: 4,
      elevation: 2,
    }),
  },
  summaryLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#747686',
  },
  rideTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: '#191C1D',
  },
  routeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  routeLabel: {
    flex: 1,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
    color: '#191C1D',
  },
  dateLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: '#434655',
    marginTop: spacing.xs,
  },
  noteCard: {
    width: '100%',
    backgroundColor: '#FFF8F7',
    borderRadius: layout.radiusLg,
    borderWidth: 1,
    borderColor: 'rgba(186, 26, 26, 0.15)',
    padding: spacing.lg,
    gap: spacing.xs,
  },
  noteLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: '#BA1A1A',
  },
  noteText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#434655',
  },
  actions: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
    gap: spacing.md,
  },
  keepButton: {
    height: 56,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: '#C4C5D7',
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  keepLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: '#434655',
  },
  confirmButton: {
    height: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: '#BA1A1A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmButtonDisabled: {
    opacity: 0.7,
  },
  confirmLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.white,
  },
});
