import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const deleteAccountTokens = {
  PRIMARY: '#0342D1',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE: '#747686',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  ERROR: '#BA1A1A',
  ERROR_SOFT: 'rgba(255, 218, 214, 0.3)',
  ERROR_BORDER: 'rgba(186, 26, 26, 0.1)',
  SELECTED_BG: 'rgba(3, 66, 209, 0.05)',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: deleteAccountTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    minHeight: 64,
    backgroundColor: deleteAccountTokens.SURFACE,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 8, offsetY: 2, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: deleteAccountTokens.PRIMARY,
    flexShrink: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.xxxl,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  warningCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.lg,
    padding: spacing.xxl,
    borderRadius: layout.radiusXl,
    backgroundColor: deleteAccountTokens.ERROR_SOFT,
    borderWidth: 1,
    borderColor: deleteAccountTokens.ERROR_BORDER,
  },
  warningMeta: {
    flex: 1,
    gap: spacing.sm,
  },
  warningTitle: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: deleteAccountTokens.ERROR,
  },
  warningBody: {
    fontSize: 16,
    lineHeight: 24,
    color: deleteAccountTokens.ON_SURFACE_VARIANT,
  },
  feedbackSection: {
    gap: spacing.xxl,
  },
  reasonsHeading: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: deleteAccountTokens.ON_SURFACE,
  },
  reasonsList: {
    gap: spacing.lg,
  },
  reasonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    padding: spacing.lg,
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: deleteAccountTokens.OUTLINE_VARIANT,
  },
  reasonRowSelected: {
    borderColor: deleteAccountTokens.PRIMARY,
    backgroundColor: deleteAccountTokens.SELECTED_BG,
  },
  reasonLabel: {
    flex: 1,
    fontSize: 16,
    lineHeight: 24,
    color: deleteAccountTokens.ON_SURFACE,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: deleteAccountTokens.OUTLINE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterSelected: {
    borderColor: deleteAccountTokens.PRIMARY,
    backgroundColor: deleteAccountTokens.PRIMARY,
  },
  radioInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.white,
  },
  feedbackBlock: {
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  feedbackLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: deleteAccountTokens.ON_SURFACE_VARIANT,
    paddingHorizontal: spacing.xs,
  },
  feedbackInput: {
    minHeight: 120,
    padding: spacing.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: deleteAccountTokens.OUTLINE_VARIANT,
    borderRadius: layout.radiusXl,
    fontSize: 16,
    lineHeight: 24,
    color: deleteAccountTokens.ON_SURFACE,
    textAlignVertical: 'top',
  },
  moodImageWrap: {
    alignItems: 'center',
    opacity: 0.8,
  },
  moodImage: {
    width: 192,
    height: 128,
    borderRadius: layout.radiusXl,
    backgroundColor: deleteAccountTokens.SURFACE_LOW,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actions: {
    gap: spacing.lg,
  },
  keepButton: {
    height: 56,
    borderRadius: layout.radiusXl,
    borderWidth: 2,
    borderColor: deleteAccountTokens.PRIMARY,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  keepLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: deleteAccountTokens.PRIMARY,
  },
  deleteButton: {
    height: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: deleteAccountTokens.ERROR,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({ color: colors.shadow, opacity: 0.15, radius: 12, offsetY: 4, elevation: 4 }),
  },
  deleteLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.white,
  },
});
