import { StyleSheet } from 'react-native';

import { colors, layout, spacing, typography } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  headerWrap: {
    backgroundColor: colors.white,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.06,
      radius: 6,
      offsetY: 2,
      elevation: 2,
    }),
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.xxxl,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxl,
  },
  hero: {
    alignItems: 'center',
    width: '100%',
    gap: spacing.md,
  },
  iconRing: {
    width: 128,
    height: 128,
    borderRadius: 64,
    borderWidth: 1,
    borderColor: 'rgba(116, 118, 134, 0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  iconCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: colors.divider,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    ...typography.title,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  subtitle: {
    ...typography.body,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textMuted,
    textAlign: 'center',
    maxWidth: 340,
  },
  infoCard: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.35)',
    borderLeftWidth: 4,
    borderLeftColor: 'rgba(3, 66, 209, 0.22)',
    padding: spacing.xl,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.05,
      radius: 12,
      offsetY: 3,
      elevation: 2,
    }),
  },
  infoText: {
    flex: 1,
    ...typography.caption,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textMuted,
  },
  actions: {
    width: '100%',
    gap: spacing.sm,
    paddingTop: spacing.md,
  },
  primaryBtn: {
    minHeight: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: colors.primary,
      opacity: 0.18,
      radius: 10,
      offsetY: 3,
      elevation: 3,
    }),
  },
  primaryLabel: {
    ...typography.button,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: colors.textInverse,
  },
  secondaryBtn: {
    minHeight: 48,
    borderRadius: layout.radiusLg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryLabel: {
    ...typography.button,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: colors.primary,
  },
});
