import { StyleSheet } from 'react-native';

import { colors, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

const PRIMARY = '#0342D1';
const ON_SURFACE = '#191C1D';
const ON_SURFACE_VARIANT = '#434655';
const OUTLINE = '#747686';
const OUTLINE_VARIANT = '#C4C5D7';
const SURFACE = '#F8F9FA';
const SECONDARY_CONTAINER = '#DADFF7';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: SURFACE,
  },
  glowTop: {
    position: 'absolute',
    top: '8%',
    left: '5%',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(3, 66, 209, 0.08)',
  },
  glowBottom: {
    position: 'absolute',
    bottom: '18%',
    right: '5%',
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(218, 223, 247, 0.35)',
  },
  header: {
    height: 64,
    paddingHorizontal: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(248,249,250,0.92)',
    ...createShadow({
      color: colors.shadow,
      opacity: 0.06,
      radius: 6,
      offsetY: 2,
      elevation: 2,
    }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: PRIMARY,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  illustrationWrap: {
    width: 160,
    height: 160,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.huge,
  },
  illustrationGlow: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(3, 66, 209, 0.05)',
  },
  iconCircle: {
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: OUTLINE_VARIANT,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.06,
      radius: 16,
      offsetY: 4,
      elevation: 3,
    }),
  },
  scheduleBadge: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: SECONDARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: colors.shadow,
      opacity: 0.1,
      radius: 8,
      offsetY: 3,
      elevation: 3,
    }),
  },
  heading: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '600',
    letterSpacing: -0.3,
    color: ON_SURFACE,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  body: {
    fontSize: 16,
    lineHeight: 24,
    color: ON_SURFACE_VARIANT,
    textAlign: 'center',
    maxWidth: 360,
    paddingHorizontal: spacing.lg,
  },
  bodyHighlight: {
    fontWeight: '700',
    color: PRIMARY,
  },
  referenceCard: {
    width: '100%',
    maxWidth: 380,
    marginTop: spacing.huge,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.xxl,
    borderWidth: 1,
    borderColor: OUTLINE_VARIANT,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.06,
      radius: 16,
      offsetY: 4,
      elevation: 3,
    }),
  },
  referenceTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  referenceText: {
    flex: 1,
  },
  referenceLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: OUTLINE,
  },
  referenceNumber: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: ON_SURFACE,
    marginTop: 4,
  },
  copyButton: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#E7E8E9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusRow: {
    marginTop: spacing.xxl,
    paddingTop: spacing.xxl,
    borderTopWidth: 1,
    borderTopColor: OUTLINE_VARIANT,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: PRIMARY,
  },
  statusText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'italic',
    color: ON_SURFACE_VARIANT,
  },
  backButton: {
    width: '100%',
    maxWidth: 380,
    marginTop: spacing.huge,
    height: 56,
    borderRadius: 999,
    backgroundColor: PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: colors.shadow,
      opacity: 0.15,
      radius: 12,
      offsetY: 6,
      elevation: 5,
    }),
  },
  backLabel: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.white,
  },
});
