import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const demoDataTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SURFACE_HIGH: '#FFFFFF',
  DANGER: '#DC2626',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: demoDataTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    minHeight: 64,
    backgroundColor: demoDataTokens.SURFACE,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '600',
    color: demoDataTokens.PRIMARY,
  },
  tabs: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.md,
  },
  tab: {
    flex: 1,
    borderRadius: layout.radiusMd,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    backgroundColor: demoDataTokens.SURFACE_LOW,
    borderWidth: 1,
    borderColor: demoDataTokens.OUTLINE_VARIANT,
    alignItems: 'center',
  },
  tabActive: {
    backgroundColor: demoDataTokens.PRIMARY_CONTAINER,
    borderColor: demoDataTokens.PRIMARY,
  },
  tabLabel: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    color: demoDataTokens.ON_SURFACE_VARIANT,
  },
  tabLabelActive: {
    color: demoDataTokens.ON_PRIMARY_CONTAINER,
  },
  tabCount: {
    fontSize: 11,
    lineHeight: 14,
    color: demoDataTokens.ON_SURFACE_VARIANT,
    marginTop: 2,
  },
  tabCountActive: {
    color: demoDataTokens.ON_PRIMARY_CONTAINER,
  },
  listContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.md,
  },
  emptyCard: {
    marginTop: spacing.xxl,
    padding: spacing.xxl,
    borderRadius: layout.radiusLg,
    backgroundColor: demoDataTokens.SURFACE_HIGH,
    borderWidth: 1,
    borderColor: demoDataTokens.OUTLINE_VARIANT,
    alignItems: 'center',
    gap: spacing.sm,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: demoDataTokens.ON_SURFACE,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: demoDataTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
  },
  card: {
    borderRadius: layout.radiusLg,
    backgroundColor: demoDataTokens.SURFACE_HIGH,
    borderWidth: 1,
    borderColor: demoDataTokens.OUTLINE_VARIANT,
    padding: spacing.lg,
    gap: spacing.xs,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 6, offsetY: 2, elevation: 1 }),
  },
  cardTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
    color: demoDataTokens.ON_SURFACE,
  },
  cardLine: {
    fontSize: 13,
    lineHeight: 18,
    color: demoDataTokens.ON_SURFACE_VARIANT,
  },
  footerBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
    backgroundColor: demoDataTokens.SURFACE,
    borderTopWidth: 1,
    borderTopColor: demoDataTokens.OUTLINE_VARIANT,
    flexDirection: 'row',
    gap: spacing.md,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: layout.radiusMd,
    borderWidth: 1,
    borderColor: demoDataTokens.OUTLINE_VARIANT,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: demoDataTokens.SURFACE_HIGH,
  },
  secondaryLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: demoDataTokens.PRIMARY,
  },
  dangerButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: layout.radiusMd,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(220, 38, 38, 0.1)',
  },
  dangerLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: demoDataTokens.DANGER,
  },
});
