import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const addVehicleTokens = {
  PRIMARY: '#0342D1',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#45464D',
  OUTLINE: '#76777D',
  OUTLINE_VARIANT: '#C6C6CD',
  SURFACE: '#F8F9FF',
  SURFACE_LOW: '#EFF4FF',
  SURFACE_CONTAINER: '#E5EEFF',
  PRIMARY_FIXED: '#DAE2FD',
  TERTIARY_FIXED: '#DADFF7',
  TERTIARY_ACCENT: '#DADFF7',
  ON_TERTIARY_FIXED: '#0342D1',
  SUCCESS: '#16A34A',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: addVehicleTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingHorizontal: 20,
    paddingVertical: spacing.sm,
    minHeight: 64,
    backgroundColor: addVehicleTokens.SURFACE,
  },
  headerTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: addVehicleTokens.PRIMARY,
    flexShrink: 1,
  },
  body: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: spacing.sm,
    paddingBottom: spacing.huge,
    gap: spacing.cardGap,
  },
  hero: {
    height: 160,
    borderRadius: layout.radiusXl,
    overflow: 'hidden',
    backgroundColor: addVehicleTokens.SURFACE_LOW,
    borderWidth: 1,
    borderColor: addVehicleTokens.OUTLINE_VARIANT,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 8, offsetY: 2, elevation: 1 }),
  },
  heroHint: {
    fontSize: 14,
    lineHeight: 20,
    color: addVehicleTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
  },
  section: {
    gap: spacing.md,
  },
  sectionHeading: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: addVehicleTokens.ON_SURFACE_VARIANT,
  },
  categoryRow: {
    flexDirection: 'row',
    gap: spacing.md,
    paddingVertical: spacing.xs,
  },
  categoryCard: {
    width: 96,
    height: 96,
    borderRadius: layout.radiusXl,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: addVehicleTokens.OUTLINE_VARIANT,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  categoryCardSelected: {
    borderColor: addVehicleTokens.PRIMARY,
    backgroundColor: addVehicleTokens.PRIMARY_FIXED,
    ...createShadow({ color: colors.shadow, opacity: 0.08, radius: 8, offsetY: 2, elevation: 2 }),
  },
  categoryLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: addVehicleTokens.ON_SURFACE,
  },
  field: {
    gap: spacing.xs,
  },
  fieldLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: addVehicleTokens.ON_SURFACE_VARIANT,
  },
  inputWrap: {
    position: 'relative',
    justifyContent: 'center',
  },
  input: {
    height: 56,
    paddingHorizontal: spacing.lg,
    paddingRight: 44,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: addVehicleTokens.OUTLINE_VARIANT,
    borderRadius: layout.radiusMd,
    fontSize: 16,
    lineHeight: 24,
    color: addVehicleTokens.ON_SURFACE,
  },
  inputIcon: {
    position: 'absolute',
    right: spacing.lg,
  },
  fieldRow: {
    flexDirection: 'row',
    gap: spacing.lg,
  },
  fieldHalf: {
    flex: 1,
    gap: spacing.xs,
  },
  documentCard: {
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: addVehicleTokens.OUTLINE_VARIANT,
    padding: spacing.lg,
    overflow: 'hidden',
  },
  documentAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 6,
    backgroundColor: addVehicleTokens.TERTIARY_ACCENT,
  },
  documentTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  documentLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.lg,
    flex: 1,
  },
  documentIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: addVehicleTokens.TERTIARY_FIXED,
    alignItems: 'center',
    justifyContent: 'center',
  },
  documentTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: addVehicleTokens.ON_SURFACE,
  },
  documentSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: addVehicleTokens.ON_SURFACE_VARIANT,
  },
  documentFooter: {
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: addVehicleTokens.OUTLINE_VARIANT,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  priorityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  priorityLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: addVehicleTokens.ON_SURFACE,
  },
  optionalLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: addVehicleTokens.ON_SURFACE_VARIANT,
  },
  uploadedLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    color: addVehicleTokens.PRIMARY,
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: spacing.lg,
    paddingBottom: spacing.lg,
    backgroundColor: colors.white,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 30, offsetY: -10, elevation: 8 }),
  },
  submitButton: {
    height: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: addVehicleTokens.PRIMARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    ...createShadow({ color: colors.shadow, opacity: 0.15, radius: 12, offsetY: 6, elevation: 4 }),
  },
  submitButtonSuccess: {
    backgroundColor: addVehicleTokens.TERTIARY_ACCENT,
  },
  submitLabel: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: colors.white,
  },
  submitLabelSuccess: {
    color: addVehicleTokens.ON_TERTIARY_FIXED,
  },
});
