import { StyleSheet } from 'react-native';
import { colors, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    minHeight: 56,
    backgroundColor: '#F8F9FF',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(198,198,205,0.5)',
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 4, offsetY: 1, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flex: 1,
  },
  title: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: colors.primary,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  content: {
    paddingHorizontal: 20,
    marginTop: -16,
    gap: spacing.cardGap,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#C6C6CD',
    padding: 16,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 12, offsetY: 4, elevation: 2 }),
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#C6C6CD',
  },
  cardHeaderLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#191C1D',
  },
  routeTimeline: {
    paddingLeft: 32,
    gap: spacing.cardGap,
    position: 'relative',
  },
  routeLine: {
    position: 'absolute',
    left: 11,
    top: 8,
    bottom: 8,
    width: 2,
    backgroundColor: '#C6C6CD',
  },
  routeStop: {
    position: 'relative',
  },
  routeDot: {
    position: 'absolute',
    left: -27,
    top: 4,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 4,
  },
  routeDotPickup: {
    borderColor: '#335EEA',
  },
  routeDotDrop: {
    borderColor: '#BA1A1A',
  },
  stopLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    letterSpacing: 0.2,
    color: '#45464D',
    marginBottom: 4,
  },
  stopValue: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#191C1D',
  },
  bentoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  scheduleCard: {
    width: '100%',
  },
  scheduleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  fieldCaption: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    letterSpacing: 0.2,
    color: '#45464D',
    marginBottom: 8,
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  timeValue: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: '#191C1D',
  },
  daysRow: {
    flexDirection: 'row',
    gap: 4,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    maxWidth: 200,
  },
  dayChip: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E0E3E5',
  },
  dayChipSelected: {
    backgroundColor: '#335EEA',
  },
  dayLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#626567',
  },
  dayLabelSelected: {
    color: '#FFFFFF',
  },
  oneTime: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: '#191C1D',
  },
  halfCard: {
    width: '48%',
    flexGrow: 1,
    flexBasis: '45%',
  },
  metricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  metricValue: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: '#191C1D',
  },
  priceCurrency: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: '#335EEA',
  },
  earningsCard: {
    backgroundColor: '#131B2E',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderLeftWidth: 4,
    borderLeftColor: '#DCE9FF',
    ...createShadow({ color: colors.shadow, opacity: 0.12, radius: 16, offsetY: 6, elevation: 6 }),
  },
  earningsCaption: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#7C839B',
    marginBottom: 4,
  },
  earningsHint: {
    fontSize: 14,
    lineHeight: 20,
    color: '#7C839B',
  },
  earningsValue: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'right',
  },
  profitableBadge: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    color: '#335EEA',
    textAlign: 'right',
    marginTop: 2,
  },
  warningCard: {
    backgroundColor: '#FFF7ED',
    borderLeftWidth: 4,
    borderLeftColor: '#D97706',
    borderRadius: 8,
    padding: 16,
    flexDirection: 'row',
    gap: 12,
  },
  warningText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: '#D97706',
  },
  warningBold: {
    fontWeight: '700',
  },
  verifiedCard: {
    backgroundColor: '#EEF2FF',
    borderLeftWidth: 4,
    borderLeftColor: '#0342D1',
    borderRadius: 8,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  verifiedText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: '#0342D1',
  },
  verifyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#335EEA',
  },
  verifyLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#335EEA',
  },
  stickyFooter: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 8, offsetY: -4, elevation: 6 }),
  },
  publishButton: {
    height: 56,
    borderRadius: 12,
    backgroundColor: '#335EEA',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    ...createShadow({ color: '#335EEA', opacity: 0.25, radius: 10, offsetY: 4, elevation: 4 }),
  },
  publishLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#FFFFFF',
  },
});
