import { StyleSheet } from 'react-native';
import { colors } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#F8F9FA',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: colors.primary,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 32,
    alignItems: 'center',
    gap: 32,
  },
  hero: {
    alignItems: 'center',
    gap: 16,
  },
  cancelIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#FFDAD6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heading: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: '#191C1D',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: '#434655',
    textAlign: 'center',
    maxWidth: 320,
  },
  summaryCard: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#C4C5D7',
    padding: 24,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  summaryTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  summaryLeft: {
    flex: 1,
    gap: 4,
  },
  summaryLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#747686',
  },
  routeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  routeLabel: {
    flex: 1,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#191C1D',
  },
  summaryRight: {
    alignItems: 'flex-end',
  },
  dateLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: colors.primary,
  },
  timeLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: '#434655',
  },
  section: {
    width: '100%',
    gap: 12,
  },
  sectionLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#434655',
    marginLeft: 4,
  },
  reasonGrid: {
    width: '100%',
    gap: 12,
  },
  reasonChip: {
    width: '100%',
    minHeight: 56,
    borderWidth: 2,
    borderColor: '#C4C5D7',
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  reasonChipSelected: {
    backgroundColor: '#335EEA',
    borderColor: '#335EEA',
  },
  reasonLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#191C1D',
    textAlign: 'center',
  },
  reasonLabelSelected: {
    color: colors.white,
  },
  commentsInput: {
    width: '100%',
    minHeight: 120,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: '#C4C5D7',
    borderRadius: 16,
    padding: 16,
    fontSize: 16,
    lineHeight: 24,
    color: '#191C1D',
  },
  warningCard: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: '#DADFF7',
    borderRadius: 16,
    padding: 16,
  },
  warningText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: '#5C6276',
  },
  warningBold: {
    fontWeight: '700',
  },
  actions: {
    width: '100%',
    gap: 16,
    paddingTop: 8,
  },
  confirmButton: {
    width: '100%',
    height: 56,
    borderRadius: 16,
    backgroundColor: '#335EEA',
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: '#335EEA',
      opacity: 0.28,
      radius: 12,
      offsetY: 6,
      elevation: 6,
    }),
  },
  confirmButtonBusy: {
    opacity: 0.85,
  },
  confirmBusyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  confirmLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.white,
  },
  backButton: {
    width: '100%',
    height: 56,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#C4C5D7',
    backgroundColor: '#F8F9FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: '#434655',
  },
});
