import { StyleSheet } from 'react-native';

import { layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const verifyAadhaarTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  PRIMARY_FIXED: '#DDE1FF',
  ON_PRIMARY: '#FFFFFF',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE: '#747686',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SURFACE_LOWEST: '#FFFFFF',
  SECONDARY_FIXED: '#DCE2F9',
  ON_SECONDARY_CONTAINER: '#5C6276',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: verifyAadhaarTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    backgroundColor: verifyAadhaarTokens.SURFACE,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: verifyAadhaarTokens.OUTLINE_VARIANT,
  },
  headerTitle: {
    flex: 1,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: verifyAadhaarTokens.PRIMARY,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.cardGap,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  heroCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xl,
    backgroundColor: verifyAadhaarTokens.SURFACE_LOWEST,
    borderRadius: layout.radiusXl,
    padding: spacing.xxl,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.3)',
    ...createShadow({ color: '#000000', opacity: 0.04, radius: 12, offsetY: 2, elevation: 2 }),
  },
  heroIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: verifyAadhaarTokens.PRIMARY_FIXED,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroText: {
    flex: 1,
    gap: spacing.sm,
  },
  heroTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: verifyAadhaarTokens.ON_SURFACE,
  },
  heroBody: {
    fontSize: 14,
    lineHeight: 20,
    color: verifyAadhaarTokens.ON_SURFACE_VARIANT,
  },
  formBlock: {
    gap: spacing.xxl,
  },
  field: {
    gap: spacing.sm,
  },
  label: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: verifyAadhaarTokens.ON_SURFACE,
    paddingHorizontal: 4,
  },
  inputWrap: {
    position: 'relative',
    justifyContent: 'center',
  },
  input: {
    width: '100%',
    height: 56,
    backgroundColor: verifyAadhaarTokens.SURFACE,
    borderWidth: 2,
    borderColor: verifyAadhaarTokens.OUTLINE_VARIANT,
    borderRadius: layout.radiusLg,
    paddingHorizontal: spacing.lg,
    paddingRight: 48,
    fontSize: 16,
    lineHeight: 24,
    color: verifyAadhaarTokens.ON_SURFACE,
  },
  inputFocused: {
    borderColor: verifyAadhaarTokens.PRIMARY_CONTAINER,
  },
  inputIcon: {
    position: 'absolute',
    right: spacing.lg,
  },
  otpNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    backgroundColor: 'rgba(220, 226, 249, 0.3)',
    borderRadius: layout.radiusLg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(192, 198, 221, 0.2)',
  },
  otpNoteText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: verifyAadhaarTokens.ON_SECONDARY_CONTAINER,
  },
  ctaButton: {
    width: '100%',
    height: 56,
    borderRadius: layout.radiusLg,
    backgroundColor: verifyAadhaarTokens.PRIMARY_CONTAINER,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({
      color: verifyAadhaarTokens.PRIMARY,
      opacity: 0.2,
      radius: 12,
      offsetY: 6,
      elevation: 5,
    }),
  },
  ctaDisabled: {
    opacity: 0.55,
  },
  ctaLabel: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: verifyAadhaarTokens.ON_PRIMARY_CONTAINER,
  },
  securityBlock: {
    marginTop: spacing.xxxl,
    alignItems: 'center',
    gap: spacing.lg,
  },
  secureBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: verifyAadhaarTokens.SURFACE_LOW,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.3)',
  },
  secureBadgeText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: verifyAadhaarTokens.ON_SURFACE_VARIANT,
  },
  secureFooter: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    color: verifyAadhaarTokens.OUTLINE,
    paddingHorizontal: spacing.xxxl,
  },
  otpCard: {
    width: '100%',
    alignItems: 'center',
    gap: spacing.xxl,
  },
  otpHero: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: verifyAadhaarTokens.PRIMARY_FIXED,
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpIntro: {
    width: '100%',
    alignItems: 'center',
    gap: spacing.md,
  },
  otpTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: verifyAadhaarTokens.PRIMARY,
    textAlign: 'center',
  },
  otpSubtitle: {
    fontSize: 15,
    lineHeight: 22,
    color: verifyAadhaarTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
    maxWidth: 320,
  },
  otpInputWrap: {
    width: '100%',
    alignItems: 'center',
  },
  hintChip: {
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    backgroundColor: verifyAadhaarTokens.SURFACE_LOW,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.35)',
  },
  hintText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    color: verifyAadhaarTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
  },
  otpActions: {
    width: '100%',
    gap: spacing.lg,
    marginTop: spacing.md,
  },
  verifyButton: {
    width: '100%',
    height: 56,
    borderRadius: layout.radiusLg,
    backgroundColor: verifyAadhaarTokens.PRIMARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({
      color: verifyAadhaarTokens.PRIMARY,
      opacity: 0.25,
      radius: 14,
      offsetY: 6,
      elevation: 6,
    }),
  },
  verifyLabel: {
    fontSize: 17,
    lineHeight: 24,
    fontWeight: '700',
    color: verifyAadhaarTokens.ON_PRIMARY,
    textAlign: 'center',
  },
  secondaryActions: {
    width: '100%',
    alignItems: 'center',
    gap: spacing.xs,
  },
  linkButton: {
    width: '100%',
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
  },
  linkLabel: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
    color: verifyAadhaarTokens.PRIMARY,
    textAlign: 'center',
  },
  linkMuted: {
    color: verifyAadhaarTokens.ON_SURFACE_VARIANT,
    fontWeight: '500',
  },
});
