import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const walletTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY: '#FFFFFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE: '#747686',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_HIGH: '#E7E8E9',
  SURFACE_LOWEST: '#FFFFFF',
  ERROR: '#BA1A1A',
  ERROR_SOFT: 'rgba(186, 26, 26, 0.12)',
  CREDIT: '#16A34A',
  CREDIT_SOFT: '#DCFCE7',
  CREDIT_ICON: '#15803D',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: walletTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    minHeight: 64,
    backgroundColor: walletTokens.SURFACE,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 8, offsetY: 2, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: walletTokens.PRIMARY,
    flexShrink: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.huge,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  balanceCard: {
    height: 224,
    borderRadius: layout.radiusXl,
    backgroundColor: walletTokens.PRIMARY_CONTAINER,
    padding: spacing.xxxl,
    justifyContent: 'space-between',
    overflow: 'hidden',
    ...createShadow({
      color: walletTokens.PRIMARY,
      opacity: 0.25,
      radius: 16,
      offsetY: 8,
      elevation: 6,
    }),
  },
  balanceGlow: {
    position: 'absolute',
    top: -40,
    right: -30,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  balanceLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: walletTokens.ON_PRIMARY,
    opacity: 0.8,
  },
  balanceValue: {
    marginTop: spacing.sm,
    fontSize: 48,
    lineHeight: 56,
    fontWeight: '700',
    letterSpacing: -0.96,
    color: walletTokens.ON_PRIMARY,
  },
  balanceFooter: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  walletNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  walletName: {
    fontSize: 14,
    lineHeight: 20,
    color: walletTokens.ON_PRIMARY,
  },
  walletIdBlock: {
    alignItems: 'flex-end',
  },
  walletIdLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: walletTokens.ON_PRIMARY,
    opacity: 0.7,
  },
  walletIdValue: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: walletTokens.ON_PRIMARY,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: spacing.xxxl,
  },
  withdrawButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: walletTokens.PRIMARY,
    paddingVertical: spacing.lg,
    borderRadius: layout.radiusMd,
    ...createShadow({
      color: walletTokens.PRIMARY,
      opacity: 0.2,
      radius: 8,
      offsetY: 4,
      elevation: 3,
    }),
  },
  addMoneyButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: walletTokens.SURFACE_LOWEST,
    borderWidth: 2,
    borderColor: walletTokens.PRIMARY,
    paddingVertical: spacing.lg,
    borderRadius: layout.radiusMd,
  },
  actionLabelPrimary: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: walletTokens.ON_PRIMARY,
  },
  actionLabelOutline: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: walletTokens.PRIMARY,
  },
  transactionsSection: {
    gap: spacing.lg,
  },
  transactionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  transactionsTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: walletTokens.ON_SURFACE,
    flexShrink: 1,
  },
  viewAllLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: walletTokens.PRIMARY,
  },
  filtersRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  filterChip: {
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    backgroundColor: walletTokens.SURFACE_HIGH,
  },
  filterChipActive: {
    backgroundColor: walletTokens.PRIMARY,
  },
  filterLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: walletTokens.ON_SURFACE_VARIANT,
  },
  filterLabelActive: {
    color: walletTokens.ON_PRIMARY,
  },
  transactionList: {
    gap: spacing.md,
  },
  transactionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.lg,
    backgroundColor: walletTokens.SURFACE_LOWEST,
    borderRadius: layout.radiusMd,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.3)',
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  transactionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
    paddingRight: spacing.md,
  },
  transactionIconDebit: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: walletTokens.ERROR_SOFT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transactionIconCredit: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: walletTokens.CREDIT_SOFT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transactionMeta: {
    flex: 1,
  },
  transactionTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: walletTokens.ON_SURFACE,
  },
  transactionDate: {
    fontSize: 14,
    lineHeight: 20,
    color: walletTokens.ON_SURFACE_VARIANT,
  },
  transactionRight: {
    alignItems: 'flex-end',
  },
  amountDebit: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: walletTokens.ERROR,
  },
  amountCredit: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: walletTokens.CREDIT,
  },
  typeLabel: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 0.5,
    color: walletTokens.OUTLINE,
    textTransform: 'capitalize',
  },
  emptyState: {
    paddingVertical: spacing.xxxl,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    lineHeight: 20,
    color: walletTokens.ON_SURFACE_VARIANT,
  },
  promoCard: {
    height: 128,
    borderRadius: layout.radiusXl,
    overflow: 'hidden',
    backgroundColor: walletTokens.SURFACE_HIGH,
    ...createShadow({ color: '#000000', opacity: 0.04, radius: 8, offsetY: 2, elevation: 1 }),
  },
  promoImage: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.4,
  },
  promoOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(3, 66, 209, 0.72)',
    justifyContent: 'center',
    paddingHorizontal: spacing.xxxl,
    gap: spacing.xs,
  },
  promoEyebrow: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: walletTokens.ON_PRIMARY,
  },
  promoTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: walletTokens.ON_PRIMARY,
  },
});
