import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const referTokens = {
  PRIMARY: '#0342D1',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SECONDARY_CONTAINER: '#DADFF7',
  ON_SECONDARY_CONTAINER: '#5C6276',
  TERTIARY_FIXED: '#DBE4ED',
  ON_TERTIARY_FIXED: '#3F484F',
  PRIMARY_FIXED: '#DDE1FF',
  ON_PRIMARY_FIXED: '#001452',
  SUCCESS: '#16A34A',
  SUCCESS_BG: '#F0FDF4',
  WAITING: '#D97706',
  WAITING_BG: '#FFFBEB',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: referTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    minHeight: 64,
    backgroundColor: referTokens.SURFACE,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 8, offsetY: 2, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: referTokens.PRIMARY,
    flexShrink: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.huge,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  hero: {
    gap: spacing.lg,
  },
  heroTitle: {
    fontSize: 40,
    lineHeight: 48,
    fontWeight: '700',
    letterSpacing: -0.8,
    color: referTokens.ON_SURFACE,
  },
  heroHighlight: {
    color: referTokens.PRIMARY,
  },
  heroSubtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: referTokens.ON_SURFACE_VARIANT,
    maxWidth: 420,
  },
  perkRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.lg,
    paddingTop: spacing.lg,
  },
  perkChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: 999,
  },
  perkPrimary: {
    backgroundColor: referTokens.SECONDARY_CONTAINER,
  },
  perkNeutral: {
    backgroundColor: referTokens.TERTIARY_FIXED,
  },
  perkLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  perkLabelPrimary: {
    color: referTokens.ON_SECONDARY_CONTAINER,
  },
  perkLabelNeutral: {
    color: referTokens.ON_TERTIARY_FIXED,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: layout.radiusLg,
    borderWidth: 1,
    borderColor: referTokens.OUTLINE_VARIANT,
    padding: spacing.xxxl,
    gap: spacing.xxxl,
    overflow: 'hidden',
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  cardEyebrow: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: referTokens.PRIMARY,
  },
  cardTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: referTokens.ON_SURFACE,
    marginTop: spacing.sm,
  },
  codeRow: {
    gap: spacing.lg,
  },
  codeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    backgroundColor: referTokens.SURFACE_LOW,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: 'rgba(3, 66, 209, 0.3)',
    borderRadius: layout.radiusXl,
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.lg,
  },
  codeText: {
    flex: 1,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    letterSpacing: 3,
    color: referTokens.ON_SURFACE,
  },
  copyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  copyLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: referTokens.PRIMARY,
  },
  copyLabelDone: {
    color: referTokens.SUCCESS,
  },
  shareButton: {
    height: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: referTokens.PRIMARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({ color: colors.shadow, opacity: 0.12, radius: 10, offsetY: 4, elevation: 3 }),
  },
  shareLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: colors.white,
  },
  historyCard: {
    backgroundColor: colors.white,
    borderRadius: layout.radiusLg,
    borderWidth: 1,
    borderColor: referTokens.OUTLINE_VARIANT,
    overflow: 'hidden',
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  historyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    padding: spacing.xxxl,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: referTokens.OUTLINE_VARIANT,
    backgroundColor: 'rgba(243, 244, 245, 0.3)',
  },
  historyTitle: {
    flex: 1,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: referTokens.ON_SURFACE,
  },
  earnedBadge: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    backgroundColor: referTokens.PRIMARY,
  },
  earnedLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: colors.white,
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    padding: spacing.xxl,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: referTokens.OUTLINE_VARIANT,
  },
  historyLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPrimary: {
    backgroundColor: referTokens.PRIMARY_FIXED,
  },
  avatarSecondary: {
    backgroundColor: '#DCE2F9',
  },
  historyMeta: {
    flex: 1,
    gap: 2,
  },
  historyName: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: referTokens.ON_SURFACE,
  },
  historyDetail: {
    fontSize: 14,
    lineHeight: 20,
    color: referTokens.ON_SURFACE_VARIANT,
  },
  historyRight: {
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  amountSuccess: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: referTokens.PRIMARY,
  },
  amountPending: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: referTokens.ON_SURFACE_VARIANT,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: 4,
  },
  statusSuccessful: {
    backgroundColor: referTokens.SUCCESS_BG,
  },
  statusWaiting: {
    backgroundColor: referTokens.WAITING_BG,
  },
  statusLabel: {
    fontSize: 12,
    fontWeight: '700',
  },
  statusLabelSuccessful: {
    color: referTokens.SUCCESS,
  },
  statusLabelWaiting: {
    color: referTokens.WAITING,
  },
  viewAllWrap: {
    padding: spacing.lg,
    alignItems: 'center',
    backgroundColor: 'rgba(243, 244, 245, 0.3)',
  },
  viewAllLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: referTokens.PRIMARY,
  },
});
