import { StyleSheet } from 'react-native';

import { layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const linkUpiTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY: '#FFFFFF',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SURFACE_LOWEST: '#FFFFFF',
  SUCCESS: '#16A34A',
  SUCCESS_BG: '#F0FDF4',
  ERROR: '#BA1A1A',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: linkUpiTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    minHeight: 64,
    backgroundColor: linkUpiTokens.SURFACE,
    ...createShadow({ color: '#000000', opacity: 0.04, radius: 8, offsetY: 2, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: linkUpiTokens.PRIMARY,
    flexShrink: 1,
  },
  avatarButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: linkUpiTokens.PRIMARY_CONTAINER,
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.cardGap,
    maxWidth: 448,
    width: '100%',
    alignSelf: 'center',
  },
  settingsCard: {
    backgroundColor: linkUpiTokens.SURFACE_LOWEST,
    borderRadius: layout.radiusXl,
    padding: spacing.xxxl,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.3)',
    gap: spacing.lg,
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 16, offsetY: 4, elevation: 2 }),
  },
  settingsHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.lg,
  },
  settingsIcon: {
    width: 48,
    height: 48,
    borderRadius: layout.radiusLg,
    backgroundColor: 'rgba(51, 94, 234, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsText: {
    flex: 1,
    gap: 4,
  },
  settingsTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: linkUpiTokens.ON_SURFACE,
  },
  settingsSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: linkUpiTokens.ON_SURFACE_VARIANT,
  },
  field: {
    gap: spacing.sm,
  },
  label: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: linkUpiTokens.ON_SURFACE_VARIANT,
  },
  inputRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'stretch',
  },
  inputWrap: {
    flex: 1,
    position: 'relative',
    justifyContent: 'center',
  },
  input: {
    backgroundColor: linkUpiTokens.SURFACE_LOW,
    borderWidth: 2,
    borderColor: 'transparent',
    borderRadius: layout.radiusLg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    paddingRight: 44,
    fontSize: 16,
    lineHeight: 24,
    color: linkUpiTokens.ON_SURFACE,
  },
  inputFocused: {
    borderColor: linkUpiTokens.PRIMARY,
  },
  inputVerified: {
    borderColor: linkUpiTokens.SUCCESS,
  },
  inputError: {
    borderColor: linkUpiTokens.ERROR,
  },
  inputIcon: {
    position: 'absolute',
    right: spacing.md,
  },
  verifyButton: {
    paddingHorizontal: spacing.xxxl,
    borderRadius: layout.radiusLg,
    backgroundColor: linkUpiTokens.PRIMARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 96,
  },
  verifyLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: linkUpiTokens.ON_PRIMARY_CONTAINER,
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.sm,
    borderRadius: layout.radiusLg,
    backgroundColor: linkUpiTokens.SUCCESS_BG,
  },
  verifiedText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: linkUpiTokens.SUCCESS,
  },
  securityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    padding: spacing.xxxl,
    borderRadius: layout.radiusXl,
    backgroundColor: linkUpiTokens.SURFACE_LOW,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: linkUpiTokens.OUTLINE_VARIANT,
  },
  securityText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: linkUpiTokens.ON_SURFACE_VARIANT,
  },
  actions: {
    marginTop: spacing.sm,
    gap: spacing.lg,
  },
  saveButton: {
    width: '100%',
    minHeight: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: linkUpiTokens.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: linkUpiTokens.PRIMARY,
      opacity: 0.2,
      radius: 12,
      offsetY: 6,
      elevation: 4,
    }),
  },
  saveButtonDisabled: {
    opacity: 0.55,
  },
  saveLabel: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    color: linkUpiTokens.ON_PRIMARY,
  },
  secureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  secureLabel: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    color: 'rgba(67, 70, 85, 0.6)',
  },
});
