import { StyleSheet } from 'react-native';
import { colors } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#F8F9FA',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(196,197,215,0.35)',
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 6, offsetY: 2, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  avatarWrap: {
    position: 'relative',
  },
  onlineDot: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#22C55E',
    borderWidth: 2,
    borderColor: '#F8F9FA',
  },
  driverName: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#191C1D',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  onlineLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#16A34A',
  },
  vehicleLabel: {
    fontSize: 10,
    color: '#434655',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  listContent: {
    paddingHorizontal: 16,
    paddingVertical: 24,
    gap: 24,
    flexGrow: 1,
  },
  dayChipWrap: {
    alignItems: 'center',
  },
  dayChip: {
    backgroundColor: '#EDEEEF',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
  },
  dayChipText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#434655',
  },
  messageBlockLeft: {
    alignItems: 'flex-start',
    maxWidth: '85%',
  },
  messageBlockRight: {
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
    maxWidth: '85%',
  },
  bubbleLeft: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: 'rgba(196,197,215,0.25)',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 4,
    padding: 16,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 6, offsetY: 2, elevation: 1 }),
  },
  bubbleRight: {
    backgroundColor: '#335EEA',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 4,
    padding: 16,
    ...createShadow({ color: '#335EEA', opacity: 0.18, radius: 8, offsetY: 3, elevation: 3 }),
  },
  messageTextLeft: {
    fontSize: 16,
    lineHeight: 24,
    color: '#191C1D',
  },
  messageTextRight: {
    fontSize: 16,
    lineHeight: 24,
    color: '#EAEBFF',
  },
  metaLeft: {
    marginTop: 4,
    marginLeft: 4,
    fontSize: 10,
    fontWeight: '500',
    color: '#434655',
  },
  metaRight: {
    marginTop: 4,
    marginRight: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaRightText: {
    fontSize: 10,
    fontWeight: '500',
    color: '#434655',
  },
  composer: {
    backgroundColor: '#F8F9FA',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(196,197,215,0.15)',
    gap: 16,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 12, offsetY: -4, elevation: 4 }),
  },
  quickRow: {
    flexDirection: 'row',
    gap: 8,
  },
  quickChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#C4C5D7',
    backgroundColor: colors.white,
  },
  quickLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: '#434655',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F3F4F5',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(196,197,215,0.35)',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  input: {
    flex: 1,
    fontSize: 16,
    lineHeight: 24,
    color: '#191C1D',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#0342D1',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
