import { StyleSheet } from 'react-native';

import { layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const successTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  PRIMARY_FIXED: '#DDE1FF',
  PRIMARY_FIXED_DIM: '#B7C4FF',
  ON_PRIMARY: '#FFFFFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE: '#747686',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SURFACE_HIGHEST: '#E1E3E4',
  SURFACE_LOWEST: '#FFFFFF',
  SECONDARY_CONTAINER: '#DADFF7',
  ON_SECONDARY_CONTAINER: '#5C6276',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: successTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    minHeight: 64,
    backgroundColor: successTokens.SURFACE_LOWEST,
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 20, offsetY: 4, elevation: 3 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: successTokens.PRIMARY,
    flexShrink: 1,
  },
  avatarButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: successTokens.PRIMARY_FIXED,
    overflow: 'hidden',
    backgroundColor: successTokens.SURFACE_LOW,
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  body: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xxxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  glow: {
    position: 'absolute',
    alignSelf: 'center',
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(3, 66, 209, 0.08)',
  },
  card: {
    backgroundColor: successTokens.SURFACE_LOWEST,
    borderRadius: layout.radiusXl,
    padding: spacing.xxxl,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.3)',
    alignItems: 'center',
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 20, offsetY: 4, elevation: 3 }),
  },
  iconWrap: {
    marginBottom: spacing.huge,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pulseRing: {
    position: 'absolute',
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: 'rgba(3, 66, 209, 0.2)',
  },
  checkCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: successTokens.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: successTokens.PRIMARY,
      opacity: 0.2,
      radius: 12,
      offsetY: 6,
      elevation: 4,
    }),
  },
  illustrationWrap: {
    width: '100%',
    maxWidth: 280,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xxxl,
  },
  illustrationStage: {
    width: 192,
    height: 192,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bankBlock: {
    position: 'absolute',
    bottom: 16,
    width: 128,
    height: 96,
    borderRadius: layout.radiusLg,
    backgroundColor: successTokens.SURFACE_HIGHEST,
    borderWidth: 2,
    borderColor: successTokens.PRIMARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moneyNodeLarge: {
    position: 'absolute',
    top: -16,
    right: -8,
    backgroundColor: successTokens.SECONDARY_CONTAINER,
    padding: spacing.md,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: 'rgba(92, 98, 118, 0.1)',
  },
  moneyNodeSmall: {
    position: 'absolute',
    top: 48,
    left: -16,
    backgroundColor: successTokens.SECONDARY_CONTAINER,
    padding: spacing.sm,
    borderRadius: layout.radiusLg,
    borderWidth: 1,
    borderColor: 'rgba(92, 98, 118, 0.1)',
  },
  title: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: successTokens.ON_SURFACE,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  bankTitle: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '600',
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: successTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
    paddingHorizontal: spacing.lg,
  },
  messageCard: {
    width: '100%',
    marginTop: spacing.lg,
    padding: spacing.xxxl,
    borderRadius: layout.radiusXl,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.3)',
  },
  messageText: {
    fontSize: 16,
    lineHeight: 24,
    color: successTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
  },
  amountHighlight: {
    fontWeight: '700',
    color: successTokens.PRIMARY,
  },
  bankHighlight: {
    fontWeight: '600',
    color: successTokens.ON_SURFACE,
  },
  bankCard: {
    marginTop: spacing.huge,
    marginBottom: spacing.huge,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.lg,
    backgroundColor: successTokens.SURFACE_LOW,
    borderRadius: layout.radiusLg,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.2)',
  },
  bankLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flex: 1,
    paddingRight: spacing.md,
    minWidth: 0,
  },
  bankIcon: {
    width: 40,
    height: 40,
    borderRadius: layout.radiusMd,
    backgroundColor: successTokens.SECONDARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bankText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  bankLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: successTokens.OUTLINE,
  },
  bankNumber: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: successTokens.ON_SURFACE,
  },
  referenceBlock: {
    alignItems: 'center',
    marginTop: spacing.lg,
  },
  referenceLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: successTokens.OUTLINE,
  },
  referenceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  referenceValue: {
    fontSize: 16,
    lineHeight: 24,
    fontFamily: 'Courier',
    fontWeight: '600',
    color: successTokens.ON_SURFACE,
  },
  copiedHint: {
    marginTop: spacing.xs,
    fontSize: 12,
    lineHeight: 16,
    color: successTokens.PRIMARY,
  },
  primaryButton: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.lg,
    backgroundColor: successTokens.PRIMARY,
    borderRadius: layout.radiusXl,
    marginTop: spacing.lg,
    ...createShadow({
      color: successTokens.PRIMARY,
      opacity: 0.2,
      radius: 12,
      offsetY: 6,
      elevation: 4,
    }),
  },
  primaryLabel: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    color: successTokens.ON_PRIMARY,
  },
  secondaryButton: {
    marginTop: spacing.lg,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
    borderRadius: layout.radiusLg,
  },
  secondaryLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: successTokens.PRIMARY,
  },
});
