import { StyleSheet } from 'react-native';
import { colors, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FF',
  },
  scrollContent: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    gap: spacing.cardGap,
  },
  hero: {
    marginBottom: 8,
    gap: 4,
  },
  heading: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: '#191C1D',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: '#45464D',
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#C6C6CD',
    padding: 16,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 8, offsetY: 2, elevation: 2 }),
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  cardHeaderLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: '#45464D',
  },
  routeBlock: {
    gap: 12,
    position: 'relative',
  },
  routeTrack: {
    position: 'absolute',
    left: 13,
    top: 40,
    bottom: 40,
    width: 1,
    backgroundColor: '#C6C6CD',
  },
  fieldGroup: {
    gap: 4,
  },
  fieldLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    letterSpacing: 0.3,
    color: '#45464D',
    paddingHorizontal: 4,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#EFF4FF',
    borderWidth: 1,
    borderColor: '#C6C6CD',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    lineHeight: 24,
    color: '#191C1D',
    padding: 0,
  },
  locationPlaceholder: {
    color: '#76777D',
  },
  gridRow: {
    flexDirection: 'row',
    gap: 16,
  },
  gridCard: {
    flex: 1,
    gap: 8,
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  timeValue: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#335EEA',
  },
  seatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  seatButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E5EEFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  seatValue: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: '#335EEA',
  },
  recurringHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  optionalBadge: {
    backgroundColor: '#DADFF7',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
  },
  optionalText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#0342D1',
  },
  daysRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 4,
  },
  dayChip: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#C6C6CD',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  dayChipSelected: {
    backgroundColor: '#335EEA',
    borderColor: '#335EEA',
  },
  dayLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: '#45464D',
  },
  dayLabelSelected: {
    color: colors.white,
  },
  hint: {
    marginTop: 8,
    fontSize: 12,
    lineHeight: 16,
    color: 'rgba(69,70,77,0.8)',
  },
  returningRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#C6C6CD',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
    backgroundColor: colors.white,
  },
  checkboxChecked: {
    backgroundColor: '#335EEA',
    borderColor: '#335EEA',
  },
  returningLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#191C1D',
  },
  returningHint: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
    color: 'rgba(69,70,77,0.8)',
  },
  priceHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  currency: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '700',
    color: '#335EEA',
  },
  priceInput: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '700',
    color: '#335EEA',
    minWidth: 100,
    marginLeft: 8,
    padding: 0,
  },
  recommendedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#DADFF7',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
  },
  recommendedText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#0342D1',
  },
  earningsBox: {
    marginTop: 16,
    padding: 12,
    backgroundColor: '#EFF4FF',
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#C6C6CD',
  },
  earningsText: {
    fontSize: 12,
    lineHeight: 16,
    color: '#45464D',
  },
  earningsValue: {
    fontWeight: '700',
    color: '#335EEA',
  },
  nextButton: {
    marginTop: 8,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#335EEA',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    ...createShadow({ color: '#335EEA', opacity: 0.28, radius: 12, offsetY: 6, elevation: 6 }),
  },
  nextLabel: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: colors.white,
  },
});
