import { StyleSheet } from 'react-native';

import { layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const trustedContactsTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE: '#747686',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SURFACE_CONTAINER: '#EDEEEF',
  SURFACE_LOWEST: '#FFFFFF',
  SECONDARY: '#585E72',
  SECONDARY_CONTAINER: '#DADFF7',
  ON_SECONDARY_CONTAINER: '#5C6276',
  ERROR: '#BA1A1A',
  ERROR_CONTAINER: '#FFDAD6',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: trustedContactsTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    minHeight: 64,
    backgroundColor: trustedContactsTokens.SURFACE,
    borderBottomWidth: 1,
    borderBottomColor: trustedContactsTokens.OUTLINE_VARIANT,
    ...createShadow({ color: '#000000', opacity: 0.04, radius: 8, offsetY: 2, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: trustedContactsTokens.PRIMARY,
    flexShrink: 1,
  },
  avatarButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: trustedContactsTokens.SECONDARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.sectionGap,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: trustedContactsTokens.ON_SURFACE_VARIANT,
  },
  list: {
    gap: spacing.cardGap,
  },
  contactCard: {
    backgroundColor: trustedContactsTokens.SURFACE_LOWEST,
    borderRadius: layout.radiusLg,
    padding: spacing.xxxl,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.3)',
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  contactTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  contactIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
    paddingRight: spacing.sm,
  },
  contactAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: 'rgba(51, 94, 234, 0.2)',
  },
  contactInitials: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: trustedContactsTokens.SECONDARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  initialsText: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: trustedContactsTokens.ON_SECONDARY_CONTAINER,
  },
  contactName: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: trustedContactsTokens.ON_SURFACE,
  },
  contactRelation: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    color: trustedContactsTokens.PRIMARY,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 2,
  },
  iconButton: {
    padding: spacing.sm,
    borderRadius: 999,
  },
  phoneRow: {
    marginTop: spacing.xxxl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  phoneLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: trustedContactsTokens.ON_SURFACE_VARIANT,
  },
  emptyCard: {
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: trustedContactsTokens.OUTLINE_VARIANT,
    borderRadius: layout.radiusLg,
    padding: spacing.xxxl,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 140,
  },
  emptyIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: trustedContactsTokens.SURFACE_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  emptyLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: trustedContactsTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
  },
  addButtonWrap: {
    alignItems: 'center',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: trustedContactsTokens.PRIMARY_CONTAINER,
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.lg,
    borderRadius: 999,
    ...createShadow({
      color: trustedContactsTokens.PRIMARY,
      opacity: 0.2,
      radius: 12,
      offsetY: 6,
      elevation: 4,
    }),
  },
  addLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: trustedContactsTokens.ON_PRIMARY_CONTAINER,
  },
});
