import { StyleSheet } from 'react-native';

import { layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const withdrawTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY: '#FFFFFF',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE: '#747686',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_HIGH: '#E7E8E9',
  SURFACE_CONTAINER: '#EDEEEF',
  SURFACE_LOWEST: '#FFFFFF',
  ACTIVE_BG: '#EAEBFF',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: withdrawTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    minHeight: 64,
    backgroundColor: withdrawTokens.SURFACE_LOWEST,
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 20, offsetY: 4, elevation: 3 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: withdrawTokens.PRIMARY,
    flexShrink: 1,
  },
  avatarButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: withdrawTokens.PRIMARY_CONTAINER,
    overflow: 'hidden',
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.xxxl,
    gap: spacing.sectionGap,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  balanceHero: {
    height: 160,
    borderRadius: layout.radiusXl,
    backgroundColor: withdrawTokens.PRIMARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  balanceGlow: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  balanceLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: withdrawTokens.ON_PRIMARY_CONTAINER,
    opacity: 0.8,
    marginBottom: spacing.xs,
  },
  balanceValue: {
    fontSize: 48,
    lineHeight: 56,
    fontWeight: '700',
    letterSpacing: -0.96,
    color: withdrawTokens.ON_PRIMARY,
  },
  balanceValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  amountSection: {
    gap: spacing.cardGap,
  },
  fieldLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: withdrawTokens.OUTLINE,
    marginBottom: spacing.sm,
  },
  amountInputWrap: {
    position: 'relative',
    justifyContent: 'center',
  },
  currencyPrefix: {
    position: 'absolute',
    left: spacing.lg,
    zIndex: 1,
  },
  amountInput: {
    width: '100%',
    paddingLeft: 56,
    paddingRight: spacing.lg,
    paddingVertical: spacing.xxxl,
    backgroundColor: withdrawTokens.SURFACE_LOWEST,
    borderWidth: 2,
    borderColor: withdrawTokens.OUTLINE_VARIANT,
    borderRadius: layout.radiusXl,
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '700',
    color: withdrawTokens.ON_SURFACE,
  },
  amountInputFocused: {
    borderColor: withdrawTokens.PRIMARY,
  },
  chipsRow: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  chip: {
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.md,
    borderRadius: 999,
    backgroundColor: withdrawTokens.SURFACE_HIGH,
  },
  chipActive: {
    backgroundColor: withdrawTokens.PRIMARY_CONTAINER,
    ...createShadow({
      color: withdrawTokens.PRIMARY,
      opacity: 0.2,
      radius: 8,
      offsetY: 4,
      elevation: 3,
    }),
  },
  chipLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: withdrawTokens.ON_SURFACE_VARIANT,
  },
  chipLabelActive: {
    color: withdrawTokens.ON_PRIMARY,
  },
  accountsSection: {
    gap: spacing.lg,
  },
  accountsList: {
    gap: spacing.md,
  },
  bankCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.lg,
    borderRadius: layout.radiusXl,
    backgroundColor: withdrawTokens.SURFACE_LOWEST,
    borderWidth: 1,
    borderColor: withdrawTokens.OUTLINE_VARIANT,
    ...createShadow({ color: '#000000', opacity: 0.04, radius: 8, offsetY: 2, elevation: 1 }),
  },
  bankCardActive: {
    borderWidth: 2,
    borderColor: withdrawTokens.PRIMARY,
    backgroundColor: withdrawTokens.ACTIVE_BG,
  },
  bankIcon: {
    width: 48,
    height: 48,
    borderRadius: layout.radiusMd,
    backgroundColor: withdrawTokens.SURFACE_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.lg,
  },
  bankIconActive: {
    backgroundColor: withdrawTokens.SURFACE_LOWEST,
    borderWidth: 1,
    borderColor: withdrawTokens.OUTLINE_VARIANT,
  },
  bankMeta: {
    flex: 1,
  },
  bankName: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: withdrawTokens.ON_SURFACE,
  },
  bankDetails: {
    fontSize: 14,
    lineHeight: 20,
    color: withdrawTokens.ON_SURFACE_VARIANT,
  },
  addAccountCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.lg,
    borderRadius: layout.radiusXl,
    backgroundColor: withdrawTokens.SURFACE_LOWEST,
    borderWidth: 1,
    borderColor: withdrawTokens.OUTLINE_VARIANT,
  },
  addAccountIcon: {
    width: 48,
    height: 48,
    borderRadius: layout.radiusMd,
    backgroundColor: withdrawTokens.PRIMARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.lg,
  },
  addAccountTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: withdrawTokens.PRIMARY,
  },
  addAccountSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: withdrawTokens.ON_SURFACE_VARIANT,
  },
  bottomBar: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    backgroundColor: withdrawTokens.SURFACE_LOWEST,
    borderTopWidth: 1,
    borderTopColor: withdrawTokens.OUTLINE_VARIANT,
  },
  proceedButton: {
    width: '100%',
    maxWidth: layout.maxContentWidth,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.lg,
    backgroundColor: withdrawTokens.PRIMARY,
    borderRadius: layout.radiusXl,
    ...createShadow({
      color: withdrawTokens.PRIMARY,
      opacity: 0.25,
      radius: 12,
      offsetY: 6,
      elevation: 4,
    }),
  },
  proceedLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: withdrawTokens.ON_PRIMARY,
  },
});
