import { StyleSheet } from 'react-native';

import { colors } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

const PRIMARY = '#0342D1';
const PRIMARY_CONTAINER = '#335EEA';
const ON_SURFACE = '#191C1D';
const ON_SURFACE_VARIANT = '#434655';
const OUTLINE = '#747686';
const OUTLINE_VARIANT = '#C4C5D7';
const SURFACE = '#F8F9FA';
const SURFACE_CONTAINER_LOW = '#F3F4F5';
const SURFACE_CONTAINER_HIGHEST = '#E1E3E4';
const RADIUS_XL = 12;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: SURFACE,
  },
  header: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    ...createShadow({ color: colors.shadow, opacity: 0.06, radius: 6, offsetY: 2, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  title: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: PRIMARY,
  },
  modeBadge: {
    backgroundColor: PRIMARY_CONTAINER,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  modeBadgeText: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#EAEBFF',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  notifyBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarRing: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: OUTLINE_VARIANT,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 32,
  },
  tabs: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: OUTLINE_VARIANT,
    marginBottom: 32,
  },
  tab: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    position: 'relative',
  },
  tabLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: ON_SURFACE_VARIANT,
  },
  tabLabelActive: {
    color: PRIMARY,
  },
  tabIndicator: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: -1,
    height: 2,
    backgroundColor: PRIMARY,
  },
  rideCard: {
    backgroundColor: colors.white,
    borderRadius: RADIUS_XL,
    borderWidth: 1,
    borderColor: OUTLINE_VARIANT,
    overflow: 'hidden',
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 4 }),
  },
  cardBody: {
    padding: 24,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
    gap: 12,
  },
  cardHeaderLeft: {
    flex: 1,
  },
  dateLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: PRIMARY,
    marginBottom: 4,
  },
  rideTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: ON_SURFACE,
  },
  assuredBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(51, 94, 234, 0.1)',
    borderWidth: 1,
    borderColor: PRIMARY_CONTAINER,
  },
  assuredText: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '700',
    color: PRIMARY,
  },
  otpBox: {
    backgroundColor: 'rgba(51, 94, 234, 0.1)',
    borderWidth: 1,
    borderColor: PRIMARY_CONTAINER,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    alignItems: 'center',
  },
  otpLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: PRIMARY,
    marginBottom: 4,
  },
  otpValue: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '800',
    letterSpacing: 4,
    color: PRIMARY,
  },
  mapRouteRow: {
    gap: 24,
  },
  mapPreview: {
    height: 160,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: SURFACE_CONTAINER_HIGHEST,
  },
  routeBlock: {
    paddingLeft: 32,
    position: 'relative',
    gap: 32,
  },
  routeLine: {
    position: 'absolute',
    left: 11,
    top: 8,
    bottom: 8,
    width: 2,
    backgroundColor: OUTLINE_VARIANT,
  },
  stopRow: {
    position: 'relative',
  },
  stopDot: {
    position: 'absolute',
    left: -32,
    top: 4,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: SURFACE_CONTAINER_HIGHEST,
    borderWidth: 4,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: PRIMARY,
  },
  stopLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: ON_SURFACE_VARIANT,
    marginBottom: 2,
  },
  stopValue: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: ON_SURFACE,
  },
  driverSection: {
    marginTop: 32,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: OUTLINE_VARIANT,
    gap: 16,
  },
  peerLabel: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: ON_SURFACE_VARIANT,
  },
  driverRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  driverAvatarRing: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: PRIMARY_CONTAINER,
    padding: 2,
    overflow: 'hidden',
  },
  driverMeta: {
    flex: 1,
  },
  driverNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  driverName: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: ON_SURFACE,
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  verifiedText: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '700',
    color: '#15803D',
  },
  vehicleText: {
    fontSize: 14,
    lineHeight: 20,
    color: ON_SURFACE_VARIANT,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: OUTLINE,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.white,
  },
  cancelLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: ON_SURFACE,
  },
  trackButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: PRIMARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    ...createShadow({ color: PRIMARY, opacity: 0.22, radius: 8, offsetY: 3, elevation: 4 }),
  },
  trackLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: colors.white,
  },
  emptyState: {
    backgroundColor: colors.white,
    borderRadius: RADIUS_XL,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.4)',
    padding: 28,
    alignItems: 'center',
    gap: 8,
  },
  emptyTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: ON_SURFACE,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: ON_SURFACE_VARIANT,
    textAlign: 'center',
  },
  historyList: {
    gap: 16,
  },
  historyCard: {
    backgroundColor: colors.white,
    borderRadius: RADIUS_XL,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.4)',
    padding: 20,
    gap: 12,
  },
  historyTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  historyTitle: {
    flex: 1,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: ON_SURFACE,
  },
  historyStatus: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: PRIMARY,
  },
  historyMeta: {
    fontSize: 14,
    lineHeight: 20,
    color: ON_SURFACE_VARIANT,
  },
  historyMetaGroup: {
    gap: 4,
  },
  dashedPlaceholder: {
    marginTop: 24,
    minHeight: 72,
    borderRadius: RADIUS_XL,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: OUTLINE_VARIANT,
    backgroundColor: 'rgba(243, 244, 245, 0.5)',
    opacity: 0.8,
  },
});

export const myRidesTokens = {
  PRIMARY,
  ON_SURFACE_VARIANT,
  PRIMARY_CONTAINER,
} as const;
