import { StyleSheet } from 'react-native';

import { colors, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FF',
  },
  header: {
    minHeight: 64,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8F9FF',
    ...createShadow({ color: colors.shadow, opacity: 0.06, radius: 6, offsetY: 2, elevation: 2 }),
  },
  brand: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: colors.primary,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: spacing.xxxl,
    alignItems: 'center',
  },
  content: {
    width: '100%',
    maxWidth: 420,
    alignItems: 'center',
  },
  iconArea: {
    width: 128,
    height: 128,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sectionGap,
  },
  ping: {
    position: 'absolute',
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: '#D3E4FE',
    opacity: 0.35,
  },
  successCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#0342D1',
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({ color: colors.shadow, opacity: 0.08, radius: 16, offsetY: 4, elevation: 6 }),
  },
  titleBlock: {
    alignItems: 'center',
    marginBottom: spacing.huge,
    paddingHorizontal: 8,
  },
  title: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '600',
    letterSpacing: -0.2,
    color: '#191C1D',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: '#45464D',
    textAlign: 'center',
  },
  section: {
    width: '100%',
    gap: spacing.cardGap,
  },
  routeCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#C6C6CD',
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 6, offsetY: 2, elevation: 2 }),
  },
  routeRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.cardGap,
  },
  routeTrack: {
    alignItems: 'center',
    paddingTop: 4,
    gap: 4,
  },
  routeDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#191C1D',
    backgroundColor: colors.white,
  },
  routeLine: {
    width: 1,
    height: 40,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#76777D',
  },
  routeStops: {
    flex: 1,
    gap: spacing.cardGap,
  },
  stopLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    letterSpacing: 0.4,
    color: '#45464D',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  stopValue: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#191C1D',
  },
  statsRow: {
    flexDirection: 'row',
    gap: spacing.cardGap,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#C6C6CD',
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 6, offsetY: 2, elevation: 2 }),
  },
  statIcon: {
    marginBottom: 8,
  },
  statLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    letterSpacing: 0.4,
    color: '#45464D',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: '#191C1D',
  },
  daysRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 8,
  },
  dayChip: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: '#DAE2FD',
  },
  dayChipLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#191C1D',
  },
  oneTime: {
    marginTop: 8,
    fontSize: 12,
    lineHeight: 16,
    color: '#45464D',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  priceValue: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: '#0342D1',
  },
  priceSuffix: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#0342D1',
    marginLeft: 4,
  },
  actions: {
    backgroundColor: colors.white,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#C6C6CD',
    paddingHorizontal: 20,
    paddingTop: spacing.cardGap,
    paddingBottom: spacing.md,
    gap: spacing.listGap,
  },
  primaryButton: {
    width: '100%',
    height: 56,
    borderRadius: 12,
    backgroundColor: '#0342D1',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    ...createShadow({ color: colors.shadow, opacity: 0.12, radius: 8, offsetY: 3, elevation: 4 }),
  },
  primaryLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    letterSpacing: 0.2,
    color: colors.white,
  },
  secondaryButton: {
    width: '100%',
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#76777D',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.white,
  },
  secondaryLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    letterSpacing: 0.2,
    color: '#191C1D',
  },
});
