import { StyleSheet } from 'react-native';
import { colors } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 64,
    backgroundColor: '#F8F9FA',
    ...createShadow({ color: colors.shadow, opacity: 0.06, radius: 8, offsetY: 2, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  brandName: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: colors.primary,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 32,
    paddingBottom: 32,
    alignItems: 'center',
  },
  content: {
    width: '100%',
    maxWidth: 448,
    gap: 32,
  },
  hero: {
    alignItems: 'center',
    gap: 8,
  },
  heading: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: '#191C1D',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: '#434655',
    textAlign: 'center',
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    padding: 24,
    alignItems: 'center',
    gap: 16,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  avatarWrap: {
    position: 'relative',
  },
  verifiedBadge: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#0342D1',
    borderWidth: 2,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverName: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    color: '#191C1D',
    textAlign: 'center',
  },
  sectionLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#434655',
    textAlign: 'center',
  },
  starsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  starButton: {
    padding: 2,
  },
  tagsBlock: {
    width: '100%',
    paddingTop: 8,
    gap: 12,
  },
  tagsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
  },
  tagChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#C4C5D7',
    backgroundColor: colors.white,
  },
  tagChipSelected: {
    backgroundColor: '#DADFF7',
    borderColor: '#DADFF7',
  },
  tagLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: '#191C1D',
  },
  tagLabelSelected: {
    color: '#5C6276',
    fontWeight: '600',
  },
  vehicleIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#DCE2F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewSection: {
    width: '100%',
    gap: 8,
  },
  reviewLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: '#191C1D',
    paddingHorizontal: 4,
  },
  reviewInput: {
    width: '100%',
    minHeight: 120,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#C4C5D7',
    backgroundColor: colors.white,
    padding: 16,
    fontSize: 16,
    lineHeight: 24,
    color: '#191C1D',
  },
  submitButton: {
    width: '100%',
    height: 56,
    borderRadius: 999,
    backgroundColor: '#0342D1',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    ...createShadow({ color: '#0342D1', opacity: 0.25, radius: 12, offsetY: 6, elevation: 6 }),
  },
  submitButtonBusy: {
    opacity: 0.7,
  },
  submitLabel: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    color: colors.white,
  },
});
