import { StyleSheet } from 'react-native';

import { layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const addMoneyTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  PRIMARY_SOFT: 'rgba(51, 94, 234, 0.1)',
  ON_PRIMARY: '#FFFFFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE: '#747686',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SURFACE_CONTAINER: '#EDEEEF',
  SURFACE_LOWEST: '#FFFFFF',
  SECONDARY_CONTAINER: '#DADFF7',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: addMoneyTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    minHeight: 64,
    backgroundColor: addMoneyTokens.SURFACE_LOWEST,
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 20, offsetY: 4, elevation: 3 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: addMoneyTokens.PRIMARY,
    flexShrink: 1,
  },
  avatarButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: addMoneyTokens.OUTLINE_VARIANT,
    overflow: 'hidden',
    backgroundColor: addMoneyTokens.SURFACE_CONTAINER,
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.cardGap,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  amountCard: {
    backgroundColor: addMoneyTokens.SURFACE_LOWEST,
    borderRadius: layout.radiusXl,
    padding: spacing.xxl,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.3)',
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  fieldLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: addMoneyTokens.ON_SURFACE_VARIANT,
    marginBottom: spacing.lg,
  },
  amountInputWrap: {
    position: 'relative',
    justifyContent: 'center',
  },
  currencyPrefix: {
    position: 'absolute',
    left: spacing.lg,
    zIndex: 1,
  },
  amountInput: {
    width: '100%',
    paddingLeft: 56,
    paddingRight: spacing.lg,
    paddingVertical: spacing.lg,
    backgroundColor: addMoneyTokens.SURFACE_LOW,
    borderWidth: 2,
    borderColor: 'transparent',
    borderRadius: layout.radiusLg,
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '600',
    color: addMoneyTokens.ON_SURFACE,
  },
  amountInputFocused: {
    borderColor: addMoneyTokens.PRIMARY,
  },
  chipsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.lg,
    paddingBottom: spacing.sm,
  },
  chip: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: addMoneyTokens.OUTLINE_VARIANT,
    backgroundColor: addMoneyTokens.SURFACE_LOWEST,
  },
  chipActive: {
    borderColor: addMoneyTokens.PRIMARY,
    backgroundColor: addMoneyTokens.PRIMARY_SOFT,
  },
  chipLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: addMoneyTokens.ON_SURFACE,
  },
  chipLabelActive: {
    color: addMoneyTokens.PRIMARY,
  },
  sourcesSection: {
    gap: spacing.lg,
  },
  sourcesList: {
    gap: spacing.md,
  },
  sourceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.lg,
    borderRadius: layout.radiusXl,
    backgroundColor: addMoneyTokens.SURFACE_LOWEST,
    borderWidth: 1,
    borderColor: addMoneyTokens.OUTLINE_VARIANT,
  },
  sourceCardActive: {
    borderColor: addMoneyTokens.PRIMARY,
    borderWidth: 2,
  },
  sourceLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
    paddingRight: spacing.md,
  },
  sourceIcon: {
    width: 40,
    height: 40,
    borderRadius: layout.radiusMd,
    backgroundColor: addMoneyTokens.SURFACE_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sourceIconUpi: {
    backgroundColor: 'rgba(218, 223, 247, 0.3)',
  },
  sourceTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: addMoneyTokens.ON_SURFACE,
  },
  sourceSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: addMoneyTokens.ON_SURFACE_VARIANT,
  },
  radioOuter: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: addMoneyTokens.OUTLINE_VARIANT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterActive: {
    borderColor: addMoneyTokens.PRIMARY,
    backgroundColor: addMoneyTokens.PRIMARY,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: addMoneyTokens.ON_PRIMARY,
  },
  linkOptions: {
    gap: spacing.lg,
    marginTop: spacing.sm,
  },
  linkCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.lg,
    borderRadius: layout.radiusXl,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: addMoneyTokens.OUTLINE_VARIANT,
    backgroundColor: 'transparent',
  },
  linkTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: addMoneyTokens.ON_SURFACE_VARIANT,
  },
  linkSubtitle: {
    fontSize: 10,
    lineHeight: 14,
    color: addMoneyTokens.ON_SURFACE_VARIANT,
    marginTop: 2,
  },
  linkTextBlock: {
    flex: 1,
  },
  actionBlock: {
    gap: spacing.lg,
    paddingTop: spacing.sm,
  },
  submitButton: {
    width: '100%',
    minHeight: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: addMoneyTokens.PRIMARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({
      color: addMoneyTokens.PRIMARY,
      opacity: 0.2,
      radius: 12,
      offsetY: 6,
      elevation: 5,
    }),
  },
  submitLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: addMoneyTokens.ON_PRIMARY,
  },
  secureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  secureNote: {
    fontSize: 14,
    lineHeight: 20,
    color: addMoneyTokens.OUTLINE,
    textAlign: 'center',
  },
});
