import { StyleSheet } from 'react-native';
import { colors } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 64,
    backgroundColor: '#F8F9FA',
    ...createShadow({ color: colors.shadow, opacity: 0.06, radius: 8, offsetY: 2, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  brandName: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: colors.primary,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 32,
    paddingBottom: 32,
    gap: 24,
  },
  hero: {
    gap: 8,
  },
  heading: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: '#191C1D',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: '#434655',
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(196,197,215,0.35)',
    padding: 24,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  summaryTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 24,
    gap: 12,
  },
  summaryLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: colors.primary,
    marginBottom: 4,
  },
  summaryDate: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '600',
    color: '#191C1D',
  },
  statusBadge: {
    backgroundColor: '#335EEA',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
  },
  statusText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: '#EAEBFF',
  },
  timeline: {
    paddingLeft: 4,
    gap: 32,
    marginBottom: 8,
  },
  timelineTrack: {
    position: 'absolute',
    left: 15,
    top: 28,
    bottom: 28,
    width: 2,
    backgroundColor: '#C4C5D7',
  },
  timelineRow: {
    flexDirection: 'row',
    gap: 16,
  },
  timelineDotPrimary: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#335EEA',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: '#DDE1FF',
  },
  timelineDotSecondary: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#585E72',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: '#DCE2F9',
  },
  locationMeta: {
    flex: 1,
  },
  locationLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: '#434655',
  },
  locationTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#191C1D',
  },
  locationAddress: {
    fontSize: 14,
    lineHeight: 20,
    color: '#434655',
  },
  summaryFooter: {
    marginTop: 24,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: '#C4C5D7',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  driverLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flex: 1,
  },
  driverLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: '#434655',
  },
  driverName: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#191C1D',
  },
  driverMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  driverMeta: {
    fontSize: 14,
    lineHeight: 20,
    color: '#585E72',
  },
  amountBlock: {
    alignItems: 'flex-end',
  },
  amountLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: '#434655',
  },
  amountValue: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '600',
    color: colors.primary,
  },
  mapCard: {
    height: 192,
    borderRadius: 16,
    overflow: 'hidden',
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  mapTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(3,66,209,0.08)',
  },
  distanceBadge: {
    position: 'absolute',
    left: 16,
    bottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.88)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
  },
  distanceText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: '#191C1D',
  },
  paymentTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: '#191C1D',
    marginBottom: 24,
  },
  paymentList: {
    gap: 12,
  },
  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#C4C5D7',
    backgroundColor: colors.white,
  },
  paymentOptionActive: {
    borderColor: '#0342D1',
    backgroundColor: '#F0F4FF',
  },
  paymentLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flex: 1,
  },
  paymentIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentIconWallet: {
    backgroundColor: 'rgba(51,94,234,0.2)',
  },
  paymentIconUpi: {
    backgroundColor: 'rgba(218,223,247,0.45)',
  },
  paymentIconCash: {
    backgroundColor: '#E7E8E9',
  },
  paymentLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#191C1D',
  },
  paymentSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: '#434655',
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#C4C5D7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterSelected: {
    borderColor: '#0342D1',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#0342D1',
  },
  dashedDivider: {
    marginVertical: 32,
    borderTopWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#C4C5D7',
  },
  fareList: {
    gap: 8,
    marginBottom: 32,
  },
  fareRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  fareLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: '#434655',
  },
  fareValue: {
    fontSize: 14,
    lineHeight: 20,
    color: '#191C1D',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(196,197,215,0.35)',
  },
  totalLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: '#191C1D',
  },
  totalValue: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: colors.primary,
  },
  payButton: {
    width: '100%',
    height: 56,
    borderRadius: 16,
    backgroundColor: '#0342D1',
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({ color: '#0342D1', opacity: 0.25, radius: 12, offsetY: 6, elevation: 6 }),
  },
  payLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.white,
  },
  secureRow: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  secureText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: '#434655',
  },
});
