import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const supportChatTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE: '#747686',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SURFACE_HIGHEST: '#E1E3E4',
  SECONDARY_CONTAINER: '#DADFF7',
  ON_SECONDARY_CONTAINER: '#5C6276',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: supportChatTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    minHeight: 64,
    backgroundColor: supportChatTokens.SURFACE,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: supportChatTokens.OUTLINE_VARIANT,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: supportChatTokens.ON_SURFACE,
    flexShrink: 1,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.xxl,
    gap: spacing.xxl,
  },
  dateWrap: {
    alignItems: 'center',
  },
  dateBadge: {
    backgroundColor: '#EDEEEF',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
  },
  dateLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: supportChatTokens.ON_SURFACE_VARIANT,
  },
  supportRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.md,
    maxWidth: '85%',
  },
  agentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: supportChatTokens.SECONDARY_CONTAINER,
  },
  supportBubble: {
    backgroundColor: supportChatTokens.SURFACE_HIGHEST,
    padding: spacing.lg,
    borderRadius: layout.radiusXl,
    borderBottomLeftRadius: 0,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  supportText: {
    fontSize: 16,
    lineHeight: 24,
    color: supportChatTokens.ON_SURFACE,
  },
  supportTime: {
    marginTop: spacing.sm,
    fontSize: 10,
    fontWeight: '500',
    color: supportChatTokens.ON_SURFACE_VARIANT,
    opacity: 0.6,
  },
  userRow: {
    alignItems: 'flex-end',
    width: '100%',
  },
  userBubble: {
    maxWidth: '85%',
    backgroundColor: supportChatTokens.PRIMARY_CONTAINER,
    padding: spacing.lg,
    borderRadius: layout.radiusXl,
    borderBottomRightRadius: 0,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  userText: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.white,
  },
  userMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  userTime: {
    fontSize: 10,
    fontWeight: '500',
    color: supportChatTokens.ON_PRIMARY_CONTAINER,
    opacity: 0.8,
  },
  typingWrap: {
    alignSelf: 'flex-start',
    backgroundColor: supportChatTokens.SURFACE_LOW,
    borderRadius: 999,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  typingLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'italic',
    color: supportChatTokens.ON_SECONDARY_CONTAINER,
  },
  typingDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  typingDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: supportChatTokens.ON_SECONDARY_CONTAINER,
  },
  composerBar: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: supportChatTokens.OUTLINE_VARIANT,
    backgroundColor: supportChatTokens.SURFACE,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
  },
  composer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: supportChatTokens.OUTLINE_VARIANT,
    borderRadius: 999,
    paddingLeft: spacing.md,
    paddingRight: spacing.sm,
    paddingVertical: spacing.sm,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 8, offsetY: 2, elevation: 1 }),
  },
  attachButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    flex: 1,
    fontSize: 16,
    lineHeight: 22,
    color: supportChatTokens.ON_SURFACE,
    paddingVertical: spacing.sm,
    maxHeight: 100,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: supportChatTokens.PRIMARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: supportChatTokens.PRIMARY_CONTAINER,
      opacity: 0.25,
      radius: 8,
      offsetY: 4,
      elevation: 3,
    }),
  },
  sendButtonDisabled: {
    opacity: 0.5,
  },
});
