import { StyleSheet } from 'react-native';

import { colors } from '@/shared/theme';
import { androidTextInputFix, createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    minHeight: 48,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8F9FA',
    borderBottomWidth: 2,
    borderBottomColor: '#FFDAD6',
    ...createShadow({
      color: '#93000A',
      opacity: 0.18,
      radius: 12,
      offsetY: 2,
      elevation: 4,
    }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  title: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: '#335EEA',
    textTransform: 'uppercase',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 32,
    gap: 32,
  },
  section: {
    gap: 24,
  },
  fields: {
    gap: 24,
  },
  field: {
    gap: 8,
  },
  label: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: '#434655',
    textTransform: 'uppercase',
  },
  labelFocused: {
    color: '#0342D1',
  },
  input: {
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#C4C5D7',
    fontSize: 16,
    lineHeight: 24,
    color: '#191C1D',
    ...androidTextInputFix,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 4, offsetY: 1, elevation: 1 }),
  },
  inputFocused: {
    borderColor: '#0342D1',
    borderWidth: 2,
  },
  inputError: {
    borderColor: '#BA1A1A',
  },
  errorText: {
    fontSize: 12,
    lineHeight: 16,
    color: '#BA1A1A',
  },
  uploadHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
  },
  uploadHint: {
    fontSize: 14,
    lineHeight: 20,
    color: '#636C74',
  },
  previewRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 8,
  },
  previewCard: {
    width: 256,
    height: 160,
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#C4C5D7',
    padding: 16,
    justifyContent: 'space-between',
    overflow: 'hidden',
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 10, offsetY: 4, elevation: 3 }),
  },
  previewBlob: {
    position: 'absolute',
    right: -16,
    top: -16,
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: 'rgba(3, 66, 209, 0.05)',
  },
  previewTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  previewAvatar: {
    width: 48,
    height: 48,
    borderRadius: 4,
    backgroundColor: '#E1E3E4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewPhoto: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 12,
  },
  previewLine: {
    height: 12,
    width: 80,
    borderRadius: 4,
    backgroundColor: '#E1E3E4',
  },
  previewLineShort: {
    height: 8,
    width: 48,
    borderRadius: 4,
    backgroundColor: '#E7E8E9',
    marginTop: 4,
  },
  previewBodyLine: {
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E7E8E9',
    marginBottom: 8,
  },
  previewFooter: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  previewBadge: {
    height: 16,
    width: 48,
    borderRadius: 4,
    backgroundColor: 'rgba(3, 66, 209, 0.2)',
  },
  previewOptional: {
    width: 256,
    height: 160,
    borderRadius: 12,
    backgroundColor: '#EDEEEF',
    borderWidth: 2,
    borderColor: '#C4C5D7',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    opacity: 0.85,
  },
  previewOptionalLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: '#747686',
    textTransform: 'uppercase',
  },
  submitButton: {
    width: '100%',
    minHeight: 64,
    borderRadius: 12,
    backgroundColor: '#0342D1',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    ...createShadow({ color: '#0342D1', opacity: 0.25, radius: 12, offsetY: 6, elevation: 6 }),
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitLabel: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '600',
    color: colors.white,
  },
});
