import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const accountDeletedTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE: '#747686',
  SECONDARY_CONTAINER: '#DADFF7',
  ON_SECONDARY_CONTAINER: '#5C6276',
  SURFACE: '#F8F9FA',
  SURFACE_HIGHEST: '#E1E3E4',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: accountDeletedTokens.SURFACE,
  },
  header: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    minHeight: 64,
  },
  brand: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '800',
    letterSpacing: -0.5,
    color: accountDeletedTokens.PRIMARY,
  },
  body: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xxxl,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  visualWrap: {
    width: 192,
    height: 192,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.huge,
  },
  glow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 96,
    backgroundColor: 'rgba(51, 94, 234, 0.12)',
  },
  checkCircle: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: accountDeletedTokens.PRIMARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: accountDeletedTokens.PRIMARY_CONTAINER,
      opacity: 0.3,
      radius: 16,
      offsetY: 8,
      elevation: 6,
    }),
  },
  waveBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    padding: spacing.md,
    borderRadius: layout.radiusMd,
    backgroundColor: 'rgba(218, 223, 247, 0.55)',
    transform: [{ rotate: '12deg' }],
  },
  cloudBadge: {
    position: 'absolute',
    bottom: 16,
    left: 4,
    padding: spacing.sm,
    borderRadius: 999,
    backgroundColor: 'rgba(225, 227, 228, 0.7)',
    transform: [{ rotate: '-6deg' }],
  },
  textBlock: {
    alignItems: 'center',
    gap: spacing.lg,
    marginBottom: spacing.huge,
  },
  title: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: accountDeletedTokens.ON_SURFACE,
    textAlign: 'center',
  },
  bodyText: {
    fontSize: 16,
    lineHeight: 24,
    color: accountDeletedTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
    maxWidth: 360,
  },
  brandInline: {
    fontWeight: '700',
    color: accountDeletedTokens.PRIMARY,
  },
  actions: {
    width: '100%',
    maxWidth: 320,
    alignItems: 'center',
    gap: spacing.lg,
  },
  homeButton: {
    width: '100%',
    height: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: accountDeletedTokens.PRIMARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({
      color: accountDeletedTokens.PRIMARY,
      opacity: 0.2,
      radius: 16,
      offsetY: 8,
      elevation: 4,
    }),
  },
  homeLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.white,
  },
  endLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    color: accountDeletedTokens.OUTLINE,
    paddingTop: spacing.lg,
  },
  footer: {
    paddingVertical: spacing.xxxl,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
  },
  copyright: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: 'rgba(67, 70, 85, 0.6)',
    textAlign: 'center',
  },
  blobBottom: {
    position: 'absolute',
    bottom: -80,
    left: -80,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(51, 94, 234, 0.06)',
  },
  blobTop: {
    position: 'absolute',
    top: -60,
    right: -60,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(218, 223, 247, 0.25)',
  },
});
