import { StyleSheet } from 'react-native';

import { colors, layout, spacing, typography } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    height: 64,
    backgroundColor: colors.surface,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.05,
      radius: 12,
      offsetY: 4,
      elevation: 2,
    }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  brandName: {
    ...typography.title,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: colors.primary,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.xxxl,
    alignItems: 'center',
    gap: spacing.xl,
  },
  hero: {
    width: '100%',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.md,
  },
  successCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
    ...createShadow({
      color: colors.primary,
      opacity: 0.22,
      radius: 14,
      offsetY: 6,
      elevation: 6,
    }),
  },
  heading: {
    ...typography.title,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  subtitle: {
    ...typography.body,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textMuted,
    textAlign: 'center',
  },
  earningsCard: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.xl,
    overflow: 'hidden',
    ...createShadow({
      color: colors.shadow,
      opacity: 0.05,
      radius: 20,
      offsetY: 4,
      elevation: 3,
    }),
  },
  earningsWatermark: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    opacity: 0.1,
  },
  earningsTop: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: spacing.xxl,
    gap: spacing.md,
  },
  earningsLabel: {
    ...typography.caption,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: colors.textMuted,
    marginBottom: 4,
  },
  earningsValue: {
    ...typography.title,
    fontSize: 40,
    lineHeight: 48,
    fontWeight: '700',
    letterSpacing: -0.5,
    color: colors.primary,
  },
  statusBadge: {
    backgroundColor: 'rgba(3, 66, 209, 0.1)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
  },
  statusText: {
    ...typography.caption,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: colors.primary,
  },
  fareList: {
    borderTopWidth: 1,
    borderStyle: 'dashed',
    borderTopColor: colors.border,
    paddingTop: spacing.xl,
    gap: spacing.md,
  },
  fareRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  fareLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    flex: 1,
  },
  fareLabel: {
    ...typography.body,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textSecondary,
  },
  fareValue: {
    ...typography.body,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  fareValueHighlight: {
    color: colors.primary,
  },
  communityCard: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    backgroundColor: 'rgba(218, 223, 247, 0.35)',
    borderWidth: 1,
    borderColor: colors.accentLight,
    borderRadius: layout.radiusXl,
    padding: spacing.xl,
  },
  communityIcon: {
    width: 40,
    height: 40,
    borderRadius: layout.radiusLg,
    backgroundColor: colors.accentLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityText: {
    flex: 1,
    ...typography.body,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textSecondary,
  },
  actions: {
    width: '100%',
    gap: spacing.md,
    paddingTop: spacing.sm,
  },
  primaryBtn: {
    minHeight: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: colors.primary,
      opacity: 0.22,
      radius: 12,
      offsetY: 4,
      elevation: 4,
    }),
  },
  primaryLabel: {
    ...typography.title,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.textInverse,
  },
  secondaryBtn: {
    minHeight: 48,
    borderRadius: layout.radiusXl,
    backgroundColor: '#E7E8E9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryLabel: {
    ...typography.body,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  mapCard: {
    width: '100%',
    height: 128,
    borderRadius: layout.radiusXl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: spacing.md,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.04,
      radius: 10,
      offsetY: 2,
      elevation: 2,
    }),
  },
  mapImage: {
    width: '100%',
    height: '100%',
  },
  mapFade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(248, 249, 250, 0.35)',
  },
});
