import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const garageTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE_VARIANT: 'rgba(196, 197, 215, 0.3)',
  SURFACE: '#F8F9FA',
  SURFACE_CONTAINER: '#EDEEEF',
  SURFACE_VARIANT: 'rgba(225, 227, 228, 0.3)',
  SECONDARY: '#585E72',
  APPROVED_BG: '#DCFCE7',
  APPROVED_TEXT: '#15803D',
  PENDING_BG: '#FFFBEB',
  PENDING_TEXT: '#D97706',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: garageTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    minHeight: 64,
    backgroundColor: garageTokens.SURFACE,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 8, offsetY: 2, elevation: 2 }),
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: garageTokens.PRIMARY,
    flexShrink: 1,
  },
  body: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.xxxl,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  hero: {
    minHeight: 168,
    borderRadius: layout.radiusXl,
    backgroundColor: garageTokens.PRIMARY_CONTAINER,
    paddingVertical: spacing.xxl,
    paddingHorizontal: spacing.xxl,
    justifyContent: 'center',
    overflow: 'hidden',
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  heroText: {
    zIndex: 1,
    maxWidth: '72%',
    gap: spacing.xs,
  },
  heroEyebrow: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: 'rgba(255, 255, 255, 0.85)',
  },
  heroTitle: {
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '700',
    color: colors.white,
  },
  heroSubtitle: {
    marginTop: spacing.xs,
    fontSize: 14,
    lineHeight: 20,
    color: 'rgba(255, 255, 255, 0.92)',
  },
  heroIcon: {
    position: 'absolute',
    right: spacing.md,
    bottom: spacing.sm,
    opacity: 0.2,
    zIndex: 0,
  },
  vehicleList: {
    gap: spacing.cardGap,
  },
  vehicleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: garageTokens.OUTLINE_VARIANT,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  vehicleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.cardGap,
    flex: 1,
  },
  vehicleIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: garageTokens.SURFACE_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehicleMeta: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xs,
  },
  vehicleName: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: garageTokens.ON_SURFACE,
  },
  vehiclePlate: {
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 1,
    color: garageTokens.ON_SURFACE_VARIANT,
    fontVariant: ['tabular-nums'],
  },
  statusBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: layout.radiusSm,
  },
  statusApproved: {
    backgroundColor: garageTokens.APPROVED_BG,
  },
  statusPending: {
    backgroundColor: garageTokens.PENDING_BG,
  },
  statusLabel: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  statusLabelApproved: {
    color: garageTokens.APPROVED_TEXT,
  },
  statusLabelPending: {
    color: garageTokens.PENDING_TEXT,
  },
  moreButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  whyCard: {
    marginTop: spacing.lg,
    borderRadius: layout.radiusXl,
    backgroundColor: garageTokens.SURFACE_VARIANT,
    overflow: 'hidden',
  },
  whyContent: {
    padding: spacing.xxl,
  },
  whyTitle: {
    marginTop: spacing.md,
    marginBottom: spacing.sm,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: garageTokens.ON_SURFACE,
  },
  whyBody: {
    fontSize: 14,
    lineHeight: 20,
    color: garageTokens.ON_SURFACE_VARIANT,
  },
  whyImage: {
    width: '100%',
    height: 160,
  },
  bottomAction: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.sm,
    backgroundColor: garageTokens.SURFACE,
  },
  addButton: {
    height: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: garageTokens.PRIMARY_CONTAINER,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({
      color: garageTokens.PRIMARY_CONTAINER,
      opacity: 0.25,
      radius: 12,
      offsetY: 6,
      elevation: 4,
    }),
  },
  addLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: garageTokens.ON_PRIMARY_CONTAINER,
  },
});
