import { StyleSheet } from 'react-native';

import { colors, layout, spacing, typography } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  headerWrap: {
    backgroundColor: colors.white,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.06,
      radius: 6,
      offsetY: 2,
      elevation: 2,
    }),
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.xxxl,
    alignItems: 'center',
    gap: spacing.xxl,
  },
  card: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.3)',
    padding: spacing.xxl,
    gap: spacing.xxl,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.05,
      radius: 20,
      offsetY: 4,
      elevation: 3,
    }),
  },
  riderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  avatar: {
    borderRadius: layout.radiusLg,
  },
  riderMeta: {
    flex: 1,
    gap: 4,
  },
  riderName: {
    ...typography.title,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  riderSubtitle: {
    ...typography.caption,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: colors.textMuted,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 2,
  },
  ratingValue: {
    ...typography.caption,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  ridesCount: {
    ...typography.caption,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textMuted,
  },
  seatsBadge: {
    marginLeft: spacing.xs,
    backgroundColor: colors.accentLight,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: layout.radiusSm,
  },
  seatsBadgeText: {
    ...typography.caption,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    backgroundColor: 'rgba(75, 84, 91, 0.08)',
    borderRadius: layout.radiusLg,
    padding: spacing.md,
  },
  infoText: {
    flex: 1,
    ...typography.caption,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textMuted,
  },
  actions: {
    width: '100%',
    gap: spacing.md,
  },
  primaryBtn: {
    minHeight: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: colors.secondary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({
      color: colors.primary,
      opacity: 0.18,
      radius: 10,
      offsetY: 3,
      elevation: 3,
    }),
  },
  primaryLabel: {
    ...typography.button,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: colors.textInverse,
  },
  secondaryBtn: {
    minHeight: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.secondary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  secondaryLabel: {
    ...typography.button,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: colors.primary,
  },
});
