import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const safetyTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  SECONDARY: '#585E72',
  OUTLINE_VARIANT: 'rgba(196, 197, 215, 0.3)',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SECONDARY_CONTAINER: '#DADFF7',
  ON_SECONDARY_CONTAINER: '#5C6276',
  ERROR: '#BA1A1A',
  ERROR_CONTAINER: '#FFDAD6',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: safetyTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    minHeight: 64,
    backgroundColor: safetyTokens.SURFACE,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: safetyTokens.PRIMARY,
    flexShrink: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.xxxl,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  section: {
    gap: spacing.lg,
  },
  sectionTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: safetyTokens.ON_SURFACE_VARIANT,
  },
  cardsStack: {
    gap: spacing.xxl,
  },
  trustedCard: {
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    padding: spacing.xxl,
    borderWidth: 1,
    borderColor: safetyTokens.OUTLINE_VARIANT,
    gap: spacing.xxl,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  trustedHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginBottom: spacing.sm,
  },
  trustedTitle: {
    flex: 1,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: safetyTokens.PRIMARY,
  },
  manageLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: safetyTokens.PRIMARY,
  },
  trustedBody: {
    fontSize: 14,
    lineHeight: 20,
    color: safetyTokens.SECONDARY,
  },
  avatarRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: colors.white,
    backgroundColor: safetyTokens.SURFACE_LOW,
  },
  avatarInitials: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: safetyTokens.SECONDARY_CONTAINER,
  },
  avatarInitialsText: {
    fontSize: 14,
    fontWeight: '700',
    color: safetyTokens.ON_SECONDARY_CONTAINER,
  },
  avatarOverlap: {
    marginLeft: -24,
  },
  addAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginLeft: -24,
    backgroundColor: 'rgba(51, 94, 234, 0.2)',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: safetyTokens.PRIMARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sosCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    padding: spacing.xxl,
    borderWidth: 2,
    borderColor: 'rgba(186, 26, 26, 0.5)',
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  sosIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: safetyTokens.ERROR_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sosTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: safetyTokens.ERROR,
  },
  sosBody: {
    marginTop: spacing.xs,
    fontSize: 14,
    lineHeight: 20,
    color: safetyTokens.SECONDARY,
  },
  reportCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.2)',
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  reportIcon: {
    width: 48,
    height: 48,
    borderRadius: layout.radiusMd,
    backgroundColor: safetyTokens.SECONDARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportMeta: {
    flex: 1,
    gap: 2,
  },
  reportTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: safetyTokens.ON_SURFACE,
  },
  reportSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: safetyTokens.SECONDARY,
  },
  chatButton: {
    height: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: safetyTokens.PRIMARY_CONTAINER,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    ...createShadow({
      color: safetyTokens.PRIMARY_CONTAINER,
      opacity: 0.25,
      radius: 12,
      offsetY: 6,
      elevation: 4,
    }),
  },
  chatLabel: {
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '600',
    color: safetyTokens.ON_PRIMARY_CONTAINER,
  },
  responseTime: {
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 20,
    color: safetyTokens.SECONDARY,
    opacity: 0.7,
  },
});
