/**
 * Top-level shared UI components (BhaiWay architecture checklist).
 * Implementations live in `src/shared/components`; this is the public entrypoint.
 *
 * Prefer: `import { Button, AppFooter } from '@/components'`
 */
export {
  Button,
  Input,
  PhoneInput,
  OTPInput,
  Header,
  ComingSoonScreen,
  KeyboardAwareScrollView,
  Avatar,
  IconButton,
  AppTopBar,
  BrandTopBar,
  ScreenIntro,
  ScreenHeader,
  Dropdown,
  DropdownField,
  NativeDatePicker,
  AppFooter,
  APP_FOOTER_ITEMS,
  SectionHeader,
  InfoBanner,
  DashedUploadCard,
  SuccessHero,
  UploadDocumentSheet,
  useUploadDocumentSheet,
  pickDocumentFromCamera,
  pickDocumentFromGallery,
  ImageUploader,
  UploadProgress,
} from '@/shared/components';

export type {
  ButtonProps,
  ButtonVariant,
  InputProps,
  PhoneInputProps,
  OTPInputProps,
  HeaderProps,
  HeaderVariant,
  ComingSoonScreenProps,
  KeyboardAwareScrollViewProps,
  AvatarProps,
  IconButtonProps,
  AppTopBarProps,
  BrandTopBarProps,
  ScreenIntroProps,
  ScreenIntroVariant,
  ScreenHeaderProps,
  DropdownProps,
  DropdownOption,
  DropdownFieldProps,
  NativeDatePickerProps,
  AppFooterProps,
  AppFooterTabId,
  AppFooterItem,
  SectionHeaderProps,
  InfoBannerProps,
  InfoBannerVariant,
  DashedUploadCardProps,
  DashedUploadCardStatus,
  SuccessHeroProps,
  UploadDocumentSheetProps,
  UploadDocumentSource,
  UploadedDocument,
  UseUploadDocumentSheetOptions,
  UseUploadDocumentSheetResult,
  ImageUploaderProps,
  UploadProgressProps,
} from '@/shared/components';
