import { StyleSheet } from 'react-native';

import { layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const addBankTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY: '#FFFFFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE: '#747686',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_BRIGHT: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SURFACE_LOWEST: '#FFFFFF',
  SECONDARY_CONTAINER: '#DADFF7',
  ON_SECONDARY_CONTAINER: '#5C6276',
  SUCCESS: '#16A34A',
  INFO_BG: 'rgba(51, 94, 234, 0.1)',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: addBankTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    minHeight: 64,
    backgroundColor: addBankTokens.SURFACE_LOWEST,
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 20, offsetY: 4, elevation: 3 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: addBankTokens.PRIMARY,
    flexShrink: 1,
  },
  avatarButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: addBankTokens.SURFACE_LOW,
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.huge,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  intro: {
    gap: spacing.sm,
  },
  title: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '600',
    letterSpacing: -0.32,
    color: addBankTokens.ON_SURFACE,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: addBankTokens.ON_SURFACE_VARIANT,
  },
  privacyCard: {
    borderRadius: layout.radiusLg,
    backgroundColor: addBankTokens.SURFACE_LOW,
    padding: spacing.xxxl,
    overflow: 'hidden',
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  privacyIcon: {
    width: 48,
    height: 48,
    borderRadius: layout.radiusXl,
    backgroundColor: addBankTokens.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xxxl,
  },
  privacyTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: addBankTokens.ON_SURFACE,
    marginBottom: spacing.lg,
  },
  privacyBody: {
    fontSize: 14,
    lineHeight: 20,
    color: addBankTokens.ON_SURFACE_VARIANT,
  },
  formCard: {
    backgroundColor: addBankTokens.SURFACE_LOWEST,
    borderRadius: layout.radiusLg,
    padding: spacing.xxxl,
    borderWidth: 1,
    borderColor: addBankTokens.OUTLINE_VARIANT,
    gap: spacing.xxxl,
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  field: {
    gap: spacing.sm,
  },
  label: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: addBankTokens.ON_SURFACE_VARIANT,
  },
  input: {
    width: '100%',
    backgroundColor: addBankTokens.SURFACE_BRIGHT,
    borderWidth: 1,
    borderColor: addBankTokens.OUTLINE_VARIANT,
    borderRadius: layout.radiusLg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    fontSize: 16,
    lineHeight: 24,
    color: addBankTokens.ON_SURFACE,
  },
  inputFocused: {
    borderWidth: 2,
    borderColor: addBankTokens.PRIMARY,
  },
  inputWithIcon: {
    paddingLeft: 44,
  },
  inputIconWrap: {
    position: 'relative',
    justifyContent: 'center',
  },
  inputIcon: {
    position: 'absolute',
    left: spacing.md,
    zIndex: 1,
  },
  ifscRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'stretch',
  },
  ifscInput: {
    flex: 1,
  },
  findButton: {
    paddingHorizontal: spacing.lg,
    backgroundColor: addBankTokens.SECONDARY_CONTAINER,
    borderRadius: layout.radiusLg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  findLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: addBankTokens.ON_SECONDARY_CONTAINER,
  },
  infoChip: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    padding: spacing.md,
    borderRadius: layout.radiusLg,
    backgroundColor: addBankTokens.INFO_BG,
  },
  infoText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: addBankTokens.PRIMARY,
  },
  submitButton: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.lg,
    borderRadius: layout.radiusXl,
    backgroundColor: addBankTokens.PRIMARY,
    ...createShadow({
      color: addBankTokens.PRIMARY,
      opacity: 0.2,
      radius: 12,
      offsetY: 6,
      elevation: 4,
    }),
  },
  submitButtonSuccess: {
    backgroundColor: addBankTokens.SUCCESS,
  },
  submitButtonDisabled: {
    opacity: 0.85,
  },
  submitLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    color: addBankTokens.ON_PRIMARY,
  },
});
