import { StyleSheet } from 'react-native';

import { colors, layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const emergencyTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SURFACE_HIGH: '#E7E8E9',
  ERROR: '#BA1A1A',
  ERROR_CONTAINER: '#FFDAD6',
  ON_ERROR_CONTAINER: '#93000A',
  SECONDARY_CONTAINER: '#DADFF7',
  ON_SECONDARY_CONTAINER: '#5C6276',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: emergencyTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    minHeight: 64,
    backgroundColor: emergencyTokens.SURFACE,
    borderBottomWidth: 2,
    borderBottomColor: emergencyTokens.ERROR_CONTAINER,
    ...createShadow({
      color: '#93000A',
      opacity: 0.2,
      radius: 15,
      offsetY: 0,
      elevation: 4,
    }),
  },
  headerTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: emergencyTokens.ERROR,
    textAlign: 'center',
    flex: 1,
  },
  exitButton: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: layout.radiusMd,
  },
  exitLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: emergencyTokens.ERROR,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.huge + spacing.xxxl,
    gap: spacing.cardGap,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  hero: {
    alignItems: 'center',
    paddingVertical: spacing.xxxl,
    gap: spacing.cardGap,
  },
  sosWrap: {
    width: 192,
    height: 192,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sosGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 96,
    backgroundColor: 'rgba(186, 26, 26, 0.2)',
    transform: [{ scale: 1.35 }],
  },
  sosButton: {
    width: 192,
    height: 192,
    borderRadius: 96,
    backgroundColor: emergencyTokens.ERROR,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({
      color: emergencyTokens.ERROR,
      opacity: 0.35,
      radius: 24,
      offsetY: 8,
      elevation: 8,
    }),
  },
  sosLabel: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '800',
    color: colors.white,
  },
  sosHint: {
    fontSize: 16,
    lineHeight: 24,
    color: emergencyTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
    maxWidth: 320,
  },
  tapHint: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: emergencyTokens.ERROR,
  },
  holdOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(25, 28, 29, 0.8)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
  },
  holdCard: {
    alignItems: 'center',
    gap: spacing.lg,
  },
  holdRingOuter: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 8,
    borderColor: emergencyTokens.ERROR_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  holdRingFill: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: emergencyTokens.ERROR,
  },
  holdLabel: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: colors.white,
  },
  rideCard: {
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    padding: spacing.xxl,
    borderWidth: 1,
    borderColor: emergencyTokens.OUTLINE_VARIANT,
    gap: spacing.lg,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 8, offsetY: 2, elevation: 1 }),
  },
  rideHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  rideSectionLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: emergencyTokens.ON_SURFACE_VARIANT,
  },
  statusBadge: {
    backgroundColor: emergencyTokens.PRIMARY_CONTAINER,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
  },
  statusLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: emergencyTokens.ON_PRIMARY_CONTAINER,
  },
  driverRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
  },
  driverAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: emergencyTokens.PRIMARY_CONTAINER,
    backgroundColor: emergencyTokens.SURFACE_HIGH,
  },
  driverName: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: emergencyTokens.ON_SURFACE,
  },
  driverMeta: {
    fontSize: 14,
    lineHeight: 20,
    color: emergencyTokens.ON_SURFACE_VARIANT,
  },
  locationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: emergencyTokens.SURFACE_LOW,
    borderRadius: layout.radiusMd,
    padding: spacing.lg,
  },
  locationMeta: {
    flex: 1,
    gap: 2,
  },
  locationLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: emergencyTokens.ON_SURFACE_VARIANT,
  },
  locationValue: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: emergencyTokens.ON_SURFACE,
  },
  mapLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: emergencyTokens.PRIMARY,
  },
  contactsSection: {
    gap: spacing.md,
  },
  contactsHeading: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: emergencyTokens.ON_SURFACE_VARIANT,
    paddingHorizontal: spacing.xs,
  },
  contactsRow: {
    flexDirection: 'row',
    gap: spacing.md,
    paddingVertical: spacing.xs,
  },
  contactCard: {
    width: 160,
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: emergencyTokens.OUTLINE_VARIANT,
    padding: spacing.lg,
    alignItems: 'center',
    gap: spacing.sm,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 8, offsetY: 2, elevation: 1 }),
  },
  contactIconError: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: emergencyTokens.ERROR_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactIconPrimary: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: emergencyTokens.SECONDARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: emergencyTokens.ON_SURFACE,
    textAlign: 'center',
  },
  callButton: {
    width: '100%',
    paddingVertical: spacing.sm,
    borderRadius: layout.radiusMd,
    backgroundColor: emergencyTokens.ERROR,
    alignItems: 'center',
  },
  alarmButton: {
    width: '100%',
    paddingVertical: spacing.sm,
    borderRadius: layout.radiusMd,
    backgroundColor: emergencyTokens.PRIMARY,
    alignItems: 'center',
  },
  contactActionLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: colors.white,
  },
  tipsCard: {
    backgroundColor: emergencyTokens.SURFACE_HIGH,
    borderRadius: layout.radiusXl,
    padding: spacing.xxl,
    gap: spacing.lg,
  },
  tipsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  tipsTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: emergencyTokens.ON_SURFACE,
  },
  tipRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.lg,
  },
  tipText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: emergencyTokens.ON_SURFACE,
  },
});
