import { StyleSheet } from 'react-native';

import { layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const upiLinkedTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY: '#FFFFFF',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  SECONDARY: '#585E72',
  SECONDARY_CONTAINER: '#DADFF7',
  OUTLINE: '#747686',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOWEST: '#FFFFFF',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: upiLinkedTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    minHeight: 64,
    backgroundColor: upiLinkedTokens.SURFACE,
    gap: spacing.md,
    ...createShadow({ color: '#000000', opacity: 0.04, radius: 8, offsetY: 2, elevation: 2 }),
  },
  headerTitle: {
    flex: 1,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: upiLinkedTokens.PRIMARY,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.huge,
    paddingBottom: spacing.huge + spacing.xxxl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    width: '100%',
    maxWidth: 420,
    alignItems: 'center',
  },
  iconOuter: {
    marginBottom: spacing.xxxl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconPulse: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(3, 66, 209, 0.05)',
  },
  iconCircle: {
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: upiLinkedTokens.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: upiLinkedTokens.PRIMARY,
      opacity: 0.25,
      radius: 24,
      offsetY: 0,
      elevation: 8,
    }),
  },
  copyBlock: {
    alignItems: 'center',
    gap: spacing.lg,
    marginBottom: spacing.huge,
    paddingHorizontal: spacing.sm,
  },
  title: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '600',
    letterSpacing: -0.3,
    color: upiLinkedTokens.ON_SURFACE,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: upiLinkedTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
    maxWidth: 320,
  },
  detailsCard: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    backgroundColor: upiLinkedTokens.SURFACE_LOWEST,
    borderWidth: 1,
    borderColor: upiLinkedTokens.OUTLINE_VARIANT,
    borderRadius: layout.radiusLg,
    padding: spacing.xxl,
    marginBottom: spacing.huge + spacing.sm,
    ...createShadow({ color: '#000000', opacity: 0.05, radius: 16, offsetY: 4, elevation: 2 }),
  },
  detailsLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
    minWidth: 0,
  },
  walletIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: upiLinkedTokens.SECONDARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailsText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  linkedLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: upiLinkedTokens.OUTLINE,
  },
  upiId: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: upiLinkedTokens.ON_SURFACE,
  },
  verifiedPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    backgroundColor: 'rgba(3, 66, 209, 0.1)',
  },
  verifiedText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: upiLinkedTokens.PRIMARY,
  },
  actions: {
    width: '100%',
    gap: spacing.lg,
  },
  primaryButton: {
    width: '100%',
    minHeight: 56,
    borderRadius: layout.radiusLg,
    backgroundColor: upiLinkedTokens.PRIMARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({ color: '#000000', opacity: 0.12, radius: 8, offsetY: 4, elevation: 3 }),
  },
  primaryLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: upiLinkedTokens.ON_PRIMARY,
  },
  secondaryButton: {
    width: '100%',
    minHeight: 56,
    borderRadius: layout.radiusLg,
    borderWidth: 1,
    borderColor: upiLinkedTokens.OUTLINE,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: upiLinkedTokens.SECONDARY,
  },
});
