import { StyleSheet } from 'react-native';

import { colors, layout, spacing, typography } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const profileTokens = {
  PRIMARY: '#0342D1',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  SURFACE: '#F8F9FA',
  SURFACE_LOW: '#F3F4F5',
  SURFACE_VARIANT: '#E1E3E4',
  OUTLINE_VARIANT: 'rgba(196, 197, 215, 0.3)',
  SUCCESS: '#0A5D4A',
  INSIGHT_BG: '#E7F3EF',
  SECONDARY_SOFT: 'rgba(218, 223, 247, 0.35)',
  SECONDARY: '#585E72',
  CARD_BORDER: 'rgba(196, 197, 215, 0.3)',
  DIVIDER: 'rgba(225, 227, 228, 0.5)',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: profileTokens.SURFACE_LOW,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    minHeight: 56,
    backgroundColor: profileTokens.SURFACE,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: profileTokens.OUTLINE_VARIANT,
    ...createShadow({ color: colors.shadow, opacity: 0.04, radius: 8, offsetY: 2, elevation: 2 }),
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: profileTokens.PRIMARY,
  },
  iconButton: {
    width: layout.minTouchTarget,
    height: layout.minTouchTarget,
    borderRadius: layout.minTouchTarget / 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.xxxl,
    gap: spacing.xxl,
    maxWidth: layout.maxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  identitySection: {
    alignItems: 'center',
    gap: spacing.md,
  },
  avatarWrap: {
    position: 'relative',
  },
  avatarRing: {
    width: 128,
    height: 128,
    borderRadius: 64,
    borderWidth: 4,
    borderColor: colors.white,
    overflow: 'hidden',
    backgroundColor: profileTokens.SURFACE_VARIANT,
    ...createShadow({ color: colors.shadow, opacity: 0.12, radius: 12, offsetY: 4, elevation: 4 }),
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  cameraButton: {
    position: 'absolute',
    right: 4,
    bottom: 4,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: profileTokens.PRIMARY,
    borderWidth: 2,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({ color: colors.shadow, opacity: 0.15, radius: 6, offsetY: 2, elevation: 3 }),
  },
  nameBlock: {
    alignItems: 'center',
    gap: spacing.xs,
  },
  name: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: profileTokens.ON_SURFACE,
    textAlign: 'center',
  },
  phone: {
    ...typography.subtitle,
    color: profileTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    width: '100%',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    borderRadius: layout.radiusXl,
    backgroundColor: profileTokens.SURFACE_LOW,
    borderWidth: 1,
    borderColor: profileTokens.OUTLINE_VARIANT,
  },
  badgeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  badgeDivider: {
    width: StyleSheet.hairlineWidth,
    height: 16,
    backgroundColor: 'rgba(196, 197, 215, 0.5)',
  },
  badgeLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  badgeSuccess: {
    color: profileTokens.SUCCESS,
  },
  badgeNeutral: {
    color: profileTokens.ON_SURFACE_VARIANT,
  },
  badgePrimary: {
    color: profileTokens.PRIMARY,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    padding: spacing.xxl,
    gap: spacing.xxl,
    borderWidth: 1,
    borderColor: profileTokens.CARD_BORDER,
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: profileTokens.ON_SURFACE,
  },
  cardLabelMuted: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: profileTokens.ON_SURFACE_VARIANT,
  },
  cardValue: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: profileTokens.PRIMARY,
  },
  linkButton: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: profileTokens.PRIMARY,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: profileTokens.SURFACE_VARIANT,
  },
  softDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: profileTokens.DIVIDER,
  },
  paymentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paymentLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    flex: 1,
  },
  paymentIcon: {
    width: 40,
    height: 40,
    borderRadius: layout.radiusMd,
    backgroundColor: 'rgba(51, 94, 234, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentTitle: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: profileTokens.ON_SURFACE,
  },
  paymentSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: profileTokens.ON_SURFACE_VARIANT,
  },
  breakdownList: {
    gap: spacing.sm,
  },
  breakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  breakdownLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: profileTokens.ON_SURFACE_VARIANT,
  },
  breakdownValue: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: profileTokens.ON_SURFACE,
  },
  insightCard: {
    backgroundColor: profileTokens.INSIGHT_BG,
    borderRadius: layout.radiusMd,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: profileTokens.OUTLINE_VARIANT,
  },
  insightRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  insightText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: profileTokens.SUCCESS,
  },
  insightBold: {
    fontWeight: '700',
  },
  menuCard: {
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: profileTokens.CARD_BORDER,
    overflow: 'hidden',
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 2 }),
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    padding: spacing.lg,
    minHeight: 76,
  },
  menuIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: profileTokens.SECONDARY_SOFT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuMeta: {
    flex: 1,
    gap: 2,
  },
  menuTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: profileTokens.ON_SURFACE,
  },
  menuSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: profileTokens.ON_SURFACE_VARIANT,
  },
  menuDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: profileTokens.DIVIDER,
    marginHorizontal: spacing.lg,
  },
  bottomActions: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
    gap: spacing.lg,
  },
  logOutButton: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xxxl,
    borderRadius: 999,
  },
  logOutLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.error,
  },
  versionLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    color: '#747686',
  },
});
