import { StyleSheet } from 'react-native';

import { colors, layout, spacing, typography } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  header: {
    minHeight: 64,
    paddingHorizontal: spacing.screenHorizontal,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceMuted,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.06,
      radius: 6,
      offsetY: 2,
      elevation: 2,
    }),
  },
  brand: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: colors.primary,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.screenHorizontal,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxxl,
  },
  hero: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  iconArea: {
    width: 96,
    height: 96,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  ping: {
    position: 'absolute',
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: colors.accentLight,
  },
  successCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: colors.shadow,
      opacity: 0.08,
      radius: 16,
      offsetY: 4,
      elevation: 6,
    }),
  },
  title: {
    ...typography.title,
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  subtitle: {
    ...typography.body,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  tripCard: {
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    marginBottom: spacing.lg,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.04,
      radius: 12,
      offsetY: 4,
      elevation: 2,
    }),
  },
  tripBody: {
    padding: spacing.md,
  },
  routeRow: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  routeTrack: {
    alignItems: 'center',
    paddingTop: 4,
    gap: 4,
  },
  routeDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  routeLine: {
    width: 2,
    flex: 1,
    minHeight: 36,
    backgroundColor: colors.border,
  },
  routeStops: {
    flex: 1,
    gap: spacing.lg,
  },
  stopLabel: {
    ...typography.caption,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: colors.textSecondary,
    marginBottom: 2,
  },
  stopValue: {
    ...typography.body,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  metaRow: {
    flexDirection: 'row',
    gap: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: spacing.md,
  },
  metaItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  metaCopy: {
    flex: 1,
    minWidth: 0,
  },
  metaLabel: {
    ...typography.caption,
    fontSize: 12,
    lineHeight: 16,
    color: colors.textSecondary,
  },
  metaValue: {
    ...typography.caption,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  fareBar: {
    backgroundColor: colors.accentLight,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fareLabel: {
    ...typography.button,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textPrimary,
  },
  fareValue: {
    ...typography.title,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: colors.primary,
  },
  vehicleCard: {
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    marginBottom: spacing.lg,
  },
  vehicleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  vehicleIcon: {
    width: 64,
    height: 48,
    borderRadius: layout.radiusMd,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehicleName: {
    ...typography.button,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textPrimary,
  },
  vehiclePlate: {
    ...typography.caption,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textSecondary,
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  chipLabel: {
    ...typography.caption,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  refundCard: {
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderLeftWidth: 4,
    borderLeftColor: colors.warning,
    padding: spacing.md,
    marginBottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.04,
      radius: 8,
      offsetY: 2,
      elevation: 2,
    }),
  },
  refundLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    minWidth: 0,
  },
  refundIcon: {
    width: 40,
    height: 40,
    borderRadius: layout.radiusMd,
    backgroundColor: colors.warningSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refundTitle: {
    ...typography.button,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textPrimary,
  },
  refundBody: {
    ...typography.caption,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textSecondary,
  },
  assuredNote: {
    marginBottom: spacing.xl,
  },
  actions: {
    gap: spacing.md,
    marginBottom: spacing.xl,
  },
  primaryButton: {
    minHeight: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.08,
      radius: 10,
      offsetY: 4,
      elevation: 4,
    }),
  },
  primaryLabel: {
    ...typography.button,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textInverse,
  },
  secondaryButton: {
    minHeight: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  secondaryLabel: {
    ...typography.button,
    fontSize: 14,
    lineHeight: 20,
    color: colors.primary,
  },
});
