import { StyleSheet } from 'react-native';

import { colors, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

const PRIMARY = '#0342D1';
const PRIMARY_CONTAINER = '#335EEA';
const ON_SURFACE = '#191C1D';
const ON_SURFACE_VARIANT = '#434655';
const OUTLINE = '#747686';
const OUTLINE_VARIANT = '#C4C5D7';
const SURFACE_CONTAINER_HIGHEST = '#E1E3E4';
const RADIUS_XL = 12;

export const styles = StyleSheet.create({
  rideCard: {
    backgroundColor: colors.white,
    borderRadius: RADIUS_XL,
    borderWidth: 1,
    borderColor: OUTLINE_VARIANT,
    overflow: 'hidden',
    ...createShadow({ color: colors.shadow, opacity: 0.05, radius: 20, offsetY: 4, elevation: 4 }),
  },
  cardBody: {
    padding: 24,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.sectionGap,
    gap: spacing.listGap,
  },
  cardHeaderLeft: {
    flex: 1,
  },
  dateLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: PRIMARY,
    marginBottom: 4,
  },
  rideTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: ON_SURFACE,
  },
  modifyChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: PRIMARY,
    backgroundColor: colors.white,
  },
  modifyChipLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    color: PRIMARY,
  },
  assuredBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(51, 94, 234, 0.1)',
    borderWidth: 1,
    borderColor: PRIMARY_CONTAINER,
  },
  assuredText: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '700',
    color: PRIMARY,
  },
  otpBox: {
    backgroundColor: 'rgba(51, 94, 234, 0.1)',
    borderWidth: 1,
    borderColor: PRIMARY_CONTAINER,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    alignItems: 'center',
  },
  otpLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: PRIMARY,
    marginBottom: 4,
  },
  otpValue: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '800',
    letterSpacing: 4,
    color: PRIMARY,
  },
  mapRouteRow: {
    gap: spacing.sectionGap,
  },
  mapPreview: {
    height: 160,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: SURFACE_CONTAINER_HIGHEST,
  },
  routeBlock: {
    paddingLeft: 32,
    position: 'relative',
    gap: spacing.sectionGap,
  },
  routeLine: {
    position: 'absolute',
    left: 11,
    top: 8,
    bottom: 8,
    width: 2,
    backgroundColor: OUTLINE_VARIANT,
  },
  stopRow: {
    position: 'relative',
  },
  stopDot: {
    position: 'absolute',
    left: -32,
    top: 4,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: SURFACE_CONTAINER_HIGHEST,
    borderWidth: 4,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: PRIMARY,
  },
  stopLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: ON_SURFACE_VARIANT,
    marginBottom: 2,
  },
  stopValue: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    color: ON_SURFACE,
  },
  driverSection: {
    marginTop: 32,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: OUTLINE_VARIANT,
    gap: spacing.cardGap,
  },
  peerLabel: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: ON_SURFACE_VARIANT,
  },
  ridersList: {
    gap: spacing.cardGap,
  },
  seatsBadge: {
    backgroundColor: '#DADFF7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  seatsBadgeText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
    color: PRIMARY,
  },
  emptyRiders: {
    gap: 4,
    paddingVertical: 4,
  },
  emptyRidersTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: ON_SURFACE_VARIANT,
  },
  emptyRidersHint: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    color: PRIMARY,
  },
  driverRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.cardGap,
  },
  driverAvatarRing: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: PRIMARY_CONTAINER,
    padding: 2,
    overflow: 'hidden',
  },
  driverMeta: {
    flex: 1,
  },
  driverNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  driverName: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: ON_SURFACE,
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  verifiedText: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '700',
    color: '#15803D',
  },
  vehicleText: {
    fontSize: 14,
    lineHeight: 20,
    color: ON_SURFACE_VARIANT,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: OUTLINE,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.white,
  },
  cancelLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: ON_SURFACE,
  },
  trackButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: PRIMARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    ...createShadow({ color: PRIMARY, opacity: 0.22, radius: 8, offsetY: 3, elevation: 4 }),
  },
  trackLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: colors.white,
  },
});
