export const CORPORATE_VERIFICATION_SCREEN = {
  title: 'Corporate Verification',
  officeDetailsTitle: 'Office Details',
  idVerificationTitle: 'ID Verification',
  companyLabel: 'Company Name',
  companyPlaceholder: 'e.g. Acme Corporation',
  emailLabel: 'Work Email Address',
  emailPlaceholder: 'name@company.com',
  uploadTitle: 'Corporate ID Card Photo',
  uploadSubtitle: 'Front view of your employee identification card.',
  uploadHint: 'Ensure all details are clearly visible',
  uploadingLabel: 'Processing ID...',
  uploadedLabel: 'ID Uploaded Successfully',
  uploadSheetTitle: 'Upload Corporate ID',
  uploadSheetSubtitle: 'Take a clear photo or choose one from your gallery.',
  backOptionalLabel: 'Back View (Optional)',
  securityTitle: 'Data Security Commitment',
  securityBody: 'Your ID is only used for verification and is never shared.',
  submitLabel: 'Send Workspace OTP',
  submittingLabel: 'Sending OTP...',
  otpTitle: 'Verify Workspace Email',
  otpSubtitle: (maskedEmail: string) =>
    `Enter the 6-digit OTP sent to your workspace email\n${maskedEmail}`,
  otpHint: 'Demo OTP',
  otpConfirmLabel: 'Verify Email',
  otpResendLabel: 'Resend OTP',
  otpBackLabel: 'Change work email',
  otpInvalidMessage: 'Incorrect OTP. Please try again.',
  otpLength: 6,
  demoOtp: '482916',
  verifyingLabel: 'Verifying...',
} as const;

export const WORK_EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
