import { StyleSheet } from 'react-native';

import { layout, spacing } from '@/shared/theme';
import { createShadow } from '@/shared/utils/platform';

export const fundsAddedTokens = {
  PRIMARY: '#0342D1',
  PRIMARY_CONTAINER: '#335EEA',
  ON_PRIMARY: '#FFFFFF',
  ON_PRIMARY_CONTAINER: '#EAEBFF',
  ON_SURFACE: '#191C1D',
  ON_SURFACE_VARIANT: '#434655',
  SECONDARY: '#585E72',
  OUTLINE_VARIANT: '#C4C5D7',
  SURFACE: '#F8F9FA',
  SURFACE_LOWEST: '#FFFFFF',
  PRIMARY_FIXED: '#DDE1FF',
} as const;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: fundsAddedTokens.SURFACE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    minHeight: 64,
    backgroundColor: fundsAddedTokens.SURFACE,
    ...createShadow({ color: '#000000', opacity: 0.04, radius: 8, offsetY: 2, elevation: 2 }),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flex: 1,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: fundsAddedTokens.PRIMARY_FIXED,
  },
  brandTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: fundsAddedTokens.PRIMARY,
    flexShrink: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.huge,
    paddingBottom: spacing.huge + spacing.xxxl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  glow: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(3, 66, 209, 0.06)',
    top: '28%',
  },
  content: {
    width: '100%',
    maxWidth: 420,
    alignItems: 'center',
    gap: spacing.xxxl,
  },
  iconWrap: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: fundsAddedTokens.PRIMARY_CONTAINER,
    alignItems: 'center',
    justifyContent: 'center',
    ...createShadow({
      color: fundsAddedTokens.PRIMARY,
      opacity: 0.28,
      radius: 20,
      offsetY: 8,
      elevation: 6,
    }),
  },
  headlines: {
    alignItems: 'center',
    gap: spacing.sm,
  },
  title: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600',
    color: fundsAddedTokens.ON_SURFACE,
    textAlign: 'center',
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  amount: {
    fontSize: 48,
    lineHeight: 56,
    fontWeight: '700',
    letterSpacing: -0.5,
    color: fundsAddedTokens.PRIMARY,
    textAlign: 'center',
  },
  amountUnderline: {
    width: 48,
    height: 4,
    borderRadius: 999,
    backgroundColor: fundsAddedTokens.PRIMARY,
    marginTop: spacing.xs,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: fundsAddedTokens.ON_SURFACE_VARIANT,
    textAlign: 'center',
    paddingHorizontal: spacing.lg,
  },
  statusCard: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.xxxl,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: fundsAddedTokens.OUTLINE_VARIANT,
    backgroundColor: fundsAddedTokens.SURFACE_LOWEST,
    ...createShadow({ color: '#000000', opacity: 0.04, radius: 16, offsetY: 4, elevation: 2 }),
  },
  statusLeft: {
    gap: spacing.xs,
    flex: 1,
    paddingRight: spacing.md,
  },
  statusLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: fundsAddedTokens.ON_SURFACE_VARIANT,
  },
  statusTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '700',
    color: fundsAddedTokens.ON_SURFACE,
  },
  statusRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  balanceValue: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    color: fundsAddedTokens.SECONDARY,
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  updatedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  updatedText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    color: fundsAddedTokens.PRIMARY,
  },
  actions: {
    width: '100%',
    gap: spacing.lg,
  },
  primaryButton: {
    width: '100%',
    minHeight: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: fundsAddedTokens.PRIMARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({
      color: fundsAddedTokens.PRIMARY,
      opacity: 0.2,
      radius: 12,
      offsetY: 6,
      elevation: 4,
    }),
  },
  primaryLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: fundsAddedTokens.ON_PRIMARY,
  },
  secondaryButton: {
    width: '100%',
    minHeight: 56,
    borderRadius: layout.radiusXl,
    backgroundColor: fundsAddedTokens.SURFACE_LOWEST,
    borderWidth: 2,
    borderColor: fundsAddedTokens.SECONDARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  secondaryLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: fundsAddedTokens.SECONDARY,
  },
  receiptLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: spacing.sm,
  },
  receiptLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.4,
    color: fundsAddedTokens.PRIMARY,
    textTransform: 'uppercase',
  },
});
