import { StyleSheet } from 'react-native';

import { colors, layout, spacing, typography } from '@/shared/theme';
import { androidTextInputFix, createShadow } from '@/shared/utils/platform';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  headerWrap: {
    backgroundColor: colors.white,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.06,
      radius: 6,
      offsetY: 2,
      elevation: 2,
    }),
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xl,
    paddingBottom: spacing.huge,
    gap: spacing.xl,
  },
  sectionTitle: {
    ...typography.caption,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: colors.textMuted,
    marginBottom: spacing.sm,
    paddingHorizontal: 2,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.35)',
    padding: spacing.lg,
    gap: spacing.md,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.04,
      radius: 10,
      offsetY: 2,
      elevation: 2,
    }),
  },
  pressableField: {
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.35)',
    borderRadius: layout.radiusLg,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    minHeight: 48,
    justifyContent: 'center',
  },
  pressableFieldActive: {
    borderColor: colors.primary,
    backgroundColor: colors.accentLight,
  },
  fieldLabel: {
    ...typography.caption,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: spacing.xs,
  },
  fieldIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  fieldValue: {
    ...typography.body,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: colors.primary,
    flex: 1,
  },
  routeInput: {
    ...typography.body,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
    color: colors.textPrimary,
    flex: 1,
    padding: 0,
    margin: 0,
    ...androidTextInputFix,
  },
  seatingRow: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  seatingCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.35)',
    padding: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...createShadow({
      color: colors.shadow,
      opacity: 0.04,
      radius: 10,
      offsetY: 2,
      elevation: 2,
    }),
  },
  seatingLabel: {
    ...typography.caption,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: colors.textSecondary,
    textAlign: 'center',
  },
  seatControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  seatBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  seatValue: {
    ...typography.title,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '700',
    color: colors.primary,
    minWidth: 28,
    textAlign: 'center',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  priceCurrency: {
    ...typography.title,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: colors.primary,
  },
  priceInput: {
    ...typography.title,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '700',
    color: colors.primary,
    textAlign: 'center',
    minWidth: 64,
    padding: 0,
    margin: 0,
    ...androidTextInputFix,
  },
  comfortRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: layout.radiusXl,
    borderWidth: 1,
    borderColor: 'rgba(196, 197, 215, 0.25)',
    padding: spacing.lg,
  },
  comfortCheck: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    marginTop: 2,
  },
  comfortCheckSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  comfortCopy: {
    flex: 1,
    gap: 2,
  },
  comfortTitle: {
    ...typography.body,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  comfortHint: {
    ...typography.caption,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textMuted,
  },
  preferenceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  preferenceItem: {
    width: '47%',
    flexGrow: 1,
  },
  vehicleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
    paddingHorizontal: 2,
  },
  addVehicle: {
    ...typography.button,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: colors.primary,
  },
  vehicleList: {
    gap: spacing.md,
  },
  footer: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    backgroundColor: colors.surface,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
});
